use std::{env, fs, path::Path};

use crate::build_lib::language_config::{discover_languages, LanguageConfig};

/// Helper function to generate parse_language match arms dynamically
fn generate_parse_language_match_arms(languages: &[LanguageConfig]) -> String {
    let mut code = String::new();
    
    // Handle English language parsing - always included
    if let Some(english_lang) = languages.iter().find(|lang| lang.dir_name == "english") {
        for (aliases, dialect_name) in &english_lang.dialect_alias_groups {
            let aliases_str = aliases.join("\" | \"");
            code.push_str(&format!("        \"{}\" => {{\n", aliases_str));
            code.push_str(&format!("            Some(Language::English(EnglishDialect::try_from_abbr(\"{}\").unwrap()))\n", dialect_name));
            code.push_str("        }\n");
        }
    }
    
    // Handle other languages
    for lang in languages {
        if lang.dir_name == "english" {
            continue; // English already handled above
        }
        
        for (aliases, dialect_name) in &lang.dialect_alias_groups {
            let aliases_str = aliases.join("\" | \"");
            
            // Add conditional compilation for non-English languages
            if let Some(feature) = &lang.feature {
                code.push_str(&format!("        #[cfg(feature = \"{}\")]\n", feature));
            }
            
            // Add the match arm
            code.push_str(&format!("        \"{}\" => {{\n", aliases_str));
            code.push_str(&format!("            Some(Language::{}({}Dialect::try_from_abbr(\"{}\").unwrap()))\n", lang.name, lang.name, dialect_name));
            code.push_str("        }\n");
        }
    }
    
    code
}

/// Generate language module file that contains all language-specific code
/// This consolidates all the #[cfg(feature)] attributes into one place
pub fn generate_language_modules(_out_dir: &Path) {
    let manifest_dir = Path::new(env!("CARGO_MANIFEST_DIR"));
    let src_dir = manifest_dir.join("src/language");

    // Discover all languages dynamically
    let languages = discover_languages(manifest_dir);

    let mut code = String::new();

    // Add header
    code.push_str("// Auto-generated by build.rs - do not edit manually\n");
    code.push_str("// This file centralizes all language-specific conditional compilation\n\n");

    // Generate module declarations
    code.push_str("pub mod dialects;\n");
    code.push_str("pub mod languages;\n");
    code.push_str("pub mod module;\n");
    code.push_str("pub mod registry;\n\n");

    // English is always included
    code.push_str("pub mod english;\n\n");

    // Optional language modules - generated from discovered languages
    for lang in &languages {
        if lang.feature.is_some() { // Skip English as it's already included
            if let Some(feature) = &lang.feature {
                code.push_str(&format!("#[cfg(feature = \"{}\")]\n", feature));
                code.push_str(&format!("pub mod {};\n\n", lang.dir_name));
            }
        }
    }

    // Re-exports
    code.push_str("pub use languages::{Language, LanguageFamily, parse_language};\n");
    code.push_str("pub use module::{LanguageDetector, LanguageModule};\n");
    code.push_str("pub use registry::{\n");
    code.push_str(
        "    ProseLanguage, add_language_specific_linters, detect_language, dictionary,\n",
    );
    code.push_str("    dictionary_for_language, new_curated_for_language, parser_for_prose, prose_language,\n");
    code.push_str("    weir_rules_lint_group,\n");
    code.push_str("};\n");

    // Write directly to mod.rs to replace the hand-written file
    let dest = src_dir.join("mod.rs");
    fs::create_dir_all(&src_dir).unwrap();
    fs::write(&dest, code).unwrap();

    // Also generate languages.rs
    generate_languages_file(&src_dir, &languages);

    println!("cargo:rerun-if-changed=src/language/mod.rs");
    println!("cargo:rerun-if-changed=build.rs");

    // Track dialect flags file for regeneration
    println!("cargo:rerun-if-changed=src/language/dialects/dialect_flags.rs");
}

/// Generate languages.rs with all the language-related code
fn generate_languages_file(src_dir: &Path, languages: &[LanguageConfig]) {
    let mut code = String::new();

    // Add auto-generated header
    code.push_str("// Auto-generated by build.rs - do not edit manually\n");
    code.push_str("//! Language support framework for Harper.\n");
    code.push_str("//!\n");
    code.push_str(
        "//! This module provides the core types for supporting multiple languages in Harper,\n",
    );
    code.push_str(
        "//! including language families and specific language variants with dialects.\n",
    );
    
    // Import Dialect trait for try_from_abbr method (removed - unused import)
    
    // English is always included
    code.push_str("use crate::language::english::dialects::EnglishDialect;\n\n");

    // Optional language dialect imports - generated from discovered languages
    for lang in languages {
        if let Some(feature) = &lang.feature {
            code.push_str(&format!("#[cfg(feature = \"{}\")]\n", feature));
            code.push_str(&format!("use crate::language::{}::dialects::{}Dialect;\n\n", lang.dir_name, lang.name));
        }
    }
    code.push_str("use serde::{Deserialize, Serialize};\n");
    code.push_str("use strum_macros::{Display, EnumCount, EnumIter, EnumString};\n\n");

    // parse_language function - dynamically generated
    code.push_str("/// Parse a language from a string representation.\n");
    code.push_str("pub fn parse_language(s: &str) -> Option<Language> {\n");
    code.push_str("    let s_lower = s.to_ascii_lowercase();\n\n");
    code.push_str("    match s_lower.as_str() {\n");
    
    // Use helper function to generate parse language logic
    let parse_language_code = generate_parse_language_match_arms(languages);
    code.push_str(&parse_language_code);
    
    code.push_str("        _ => None,\n");
    code.push_str("    }\n");
    code.push_str("}\n\n");

    // Language enum
    code.push_str("/// A specific language with its dialects.\n");
    code.push_str("#[derive(\n");
    code.push_str("    Debug, Clone, Copy, Serialize, Deserialize, PartialEq, PartialOrd, Eq, Hash, EnumCount, Display,\n");
    code.push_str(")]\n");
    code.push_str("pub enum Language {\n");
    
    // Generate Language enum variants dynamically
    for lang in languages {
        if lang.dir_name == "english" {
            code.push_str("    /// English language with its dialects\n");
            code.push_str("    English(EnglishDialect),\n");
        } else {
            code.push_str(&format!("    /// {} language with its dialects\n", lang.name));
            if let Some(feature) = &lang.feature {
                code.push_str(&format!("    #[cfg(feature = \"{}\")]\n", feature));
            }
            code.push_str(&format!("    {}({}Dialect),\n", lang.name, lang.name));
        }
    }
    code.push_str("}\n\n");

    // LanguageFamily enum
    code.push_str("/// A family of languages.\n");
    code.push_str("#[derive(\n");
    code.push_str("    Default,\n");
    code.push_str("    Debug,\n");
    code.push_str("    Clone,\n");
    code.push_str("    Copy,\n");
    code.push_str("    Serialize,\n");
    code.push_str("    Deserialize,\n");
    code.push_str("    PartialEq,\n");
    code.push_str("    PartialOrd,\n");
    code.push_str("    Eq,\n");
    code.push_str("    Hash,\n");
    code.push_str("    EnumCount,\n");
    code.push_str("    EnumString,\n");
    code.push_str("    EnumIter,\n");
    code.push_str("    Display,\n");
    code.push_str(")]\n");
    code.push_str("pub enum LanguageFamily {\n");
    
    // Generate LanguageFamily enum variants dynamically
    for (i, lang) in languages.iter().enumerate() {
        if i == 0 {
            code.push_str("    #[default]\n");
        }
        if lang.dir_name == "english" {
            code.push_str("    English,\n");
        } else {
            if let Some(feature) = &lang.feature {
                code.push_str(&format!("    #[cfg(feature = \"{}\")]\n", feature));
            }
            code.push_str(&format!("    {},\n", lang.name));
        }
    }
    code.push_str("}\n\n");

    // From<Language> for LanguageFamily
    code.push_str("impl From<Language> for LanguageFamily {\n");
    code.push_str("    fn from(value: Language) -> Self {\n");
    code.push_str("        match value {\n");
    
    for lang in languages {
        if lang.dir_name == "english" {
            code.push_str("            Language::English(_) => Self::English,\n");
        } else {
            if let Some(feature) = &lang.feature {
                code.push_str(&format!("            #[cfg(feature = \"{}\")]\n", feature));
            }
            code.push_str(&format!("            Language::{}(_) => Self::{},\n", lang.name, lang.name));
        }
    }
    code.push_str("        }\n");
    code.push_str("    }\n");
    code.push_str("}\n\n");

    // LanguageFamily impl
    code.push_str("impl LanguageFamily {\n");
    code.push_str("    pub fn dict_suffix(&self) -> &'static str {\n");
    code.push_str("        match self {\n");
    
    for lang in languages {
        if lang.dir_name == "english" {
            code.push_str("            Self::English => \"\",\n");
        } else {
            if let Some(feature) = &lang.feature {
                code.push_str(&format!("            #[cfg(feature = \"{}\")]\n", feature));
            }
            code.push_str(&format!("            Self::{0} => \"-{1}\",\n", lang.name, feature_to_suffix(lang)));
        }
    }
    code.push_str("        }\n");
    code.push_str("    }\n");
    code.push_str("}\n\n");

    // Language impl
    code.push_str("impl Language {\n");
    code.push_str("    pub fn family(&self) -> LanguageFamily {\n");
    code.push_str("        (*self).into()\n");
    code.push_str("    }\n");
    code.push_str("}\n\n");

    code.push_str("impl Default for Language {\n");
    code.push_str("    fn default() -> Self {\n");
    code.push_str("        Self::English(EnglishDialect::American)\n");
    code.push_str("    }\n");
    code.push_str("}\n");

    let dest = src_dir.join("languages.rs");
    fs::write(&dest, code).unwrap();

    // Also generate registry.rs
    generate_registry_file(&src_dir, &languages);
}

/// Helper function to convert feature name to dict suffix
/// e.g., "de" -> "de", "pt" -> "pt", "sk" -> "sk"
fn feature_to_suffix(lang: &LanguageConfig) -> String {
    if let Some(feature) = &lang.feature {
        feature.to_string()
    } else if lang.dir_name == "english" {
        "en".to_string()
    } else {
        lang.dir_name.to_string()
    }
}

/// Generate registry.rs with all language-specific registry code
fn generate_registry_file(src_dir: &Path, languages: &[LanguageConfig]) {
    let mut code = String::new();

    // Add auto-generated header
    code.push_str("// Auto-generated by build.rs - do not edit manually\n");
    code.push_str(
        "//! Language registry - central integration point using LanguageModule trait.\n",
    );
    code.push_str("//!\n");
    code.push_str(
        "//! This module provides all orchestration functions for language support.\n",
    );
    code.push_str(
        "//! It is the only place that imports concrete language module implementations.\n\n",
    );

    code.push_str("use std::fmt::Debug;\n");
    code.push_str("use std::sync::{Arc, LazyLock};\n\n");

    code.push_str("use super::languages::{Language, LanguageFamily};\n");
    code.push_str("use crate::spell::{Dictionary, FstDictionary};\n");
    code.push_str("use crate::{\n");
    code.push_str("    LintGroup,\n");
    code.push_str("    parsers::{Markdown, MarkdownOptions, OrgMode, Parser},\n");
    code.push_str("};\n\n");

    code.push_str("use super::english::module::EnglishModule;\n");
    code.push_str("use super::module::{LanguageDetector, LanguageModule};\n\n");

    // Import all language modules dynamically
    for lang in languages {
        if lang.dir_name == "english" {
            continue; // English already imported above
        }
        
        if let Some(feature) = &lang.feature {
            code.push_str(&format!("#[cfg(feature = \"{}\")]\n", feature));
        }
        code.push_str(&format!("use super::{}::module::{}Module;\n\n", lang.dir_name, lang.name));
    }

    // DETECTION
    code.push_str("/// All language detectors, sorted by confidence (highest to lowest).\n");
    code.push_str("#[allow(clippy::vec_init_then_push)]\n");
    code.push_str(
        "static DETECTORS: LazyLock<Vec<(Box<dyn LanguageDetector>, f64)>> = LazyLock::new(|| {\n",
    );
    code.push_str("    let mut detectors: Vec<(Box<dyn LanguageDetector>, f64)> = Vec::new();\n\n");

    // Generate detector registrations dynamically, sorted by confidence (highest first)
    let mut sorted_languages = languages.to_vec();
    sorted_languages.sort_by(|a, b| b.confidence.partial_cmp(&a.confidence).unwrap_or(std::cmp::Ordering::Equal));
    
    for lang in &sorted_languages {
        if lang.dir_name == "english" {
            continue; // English detector added last (lowest confidence)
        }
        
        if let Some(feature) = &lang.feature {
            code.push_str(&format!("    #[cfg(feature = \"{}\")]\n", feature));
        }
        code.push_str(&format!("    detectors.push((Box::new({}Module::detector()), {:.2}));\n\n", lang.name, lang.confidence));
    }
    
    // English detector always added last
    code.push_str("    detectors.push((Box::new(EnglishModule::detector()), 0.30));\n\n");
    code.push_str("    detectors\n");
    code.push_str("});\n\n");

    // detect_language function
    code.push_str("/// Detect the language of the given source text.\n");
    code.push_str("pub fn detect_language(source: &str, dict: &FstDictionary, default_language: Language) -> Language {\n");
    code.push_str("    use crate::parsers::PlainEnglish;\n\n");
    code.push_str("    let source_chars: Vec<char> = source.chars().collect();\n");
    code.push_str("    let tokens = PlainEnglish.parse(&source_chars);\n\n");

    code.push_str("    if tokens.is_empty() {\n");
    code.push_str("        return default_language;\n");
    code.push_str("    }\n\n");

    code.push_str("    for (detector, _confidence) in DETECTORS.iter() {\n");
    code.push_str(
        "        if let Some(language) = detector.detect(&tokens, &source_chars, dict) {\n",
    );
    code.push_str("            return language;\n");
    code.push_str("        }\n");
    code.push_str("    }\n");
    code.push_str("    default_language\n");
    code.push_str("}\n\n");

    // PROSE LANGUAGE
    code.push_str("/// Prose languages supported by Harper for text parsing.\n");
    code.push_str("#[derive(Clone, Copy, Debug, Eq, PartialEq)]\n");
    code.push_str("pub enum ProseLanguage {\n");
    
    // Generate ProseLanguage enum variants dynamically
    for (i, lang) in languages.iter().enumerate() {
        if i > 0 {
            if let Some(feature) = &lang.feature {
                code.push_str(&format!("    #[cfg(feature = \"{}\")]\n", feature));
            }
        }
        code.push_str(&format!("    {},", lang.name));
        if i < languages.len() - 1 {
            code.push_str("\n");
        }
    }
    code.push_str("}\n\n");

    code.push_str("/// Convert a Harper Language to a ProseLanguage.\n");
    code.push_str("pub fn prose_language(language: &Language) -> ProseLanguage {\n");
    code.push_str("    match language {\n");
    
    for lang in languages {
        if lang.dir_name == "english" {
            code.push_str("        Language::English(_) => ProseLanguage::English,\n");
        } else {
            if let Some(feature) = &lang.feature {
                code.push_str(&format!("        #[cfg(feature = \"{}\")]\n", feature));
            }
            code.push_str(&format!("        Language::{}(_) => ProseLanguage::{},\n", lang.name, lang.name));
        }
    }
    code.push_str("    }\n");
    code.push_str("}\n\n");

    // DICTIONARIES
    code.push_str("/// Get the dictionary for a language family.\n");
    code.push_str(
        "pub fn dictionary_for_language(family: LanguageFamily) -> Arc<FstDictionary> {\n",
    );
    code.push_str("    match family {\n");
    
    for lang in languages {
        if lang.dir_name == "english" {
            code.push_str("        LanguageFamily::English => EnglishModule::dictionary(),\n");
        } else {
            if let Some(feature) = &lang.feature {
                code.push_str(&format!("        #[cfg(feature = \"{}\")]\n", feature));
            }
            code.push_str(&format!("        LanguageFamily::{0} => {1}Module::dictionary(),\n", lang.name, lang.name));
        }
    }
    code.push_str("    }\n");
    code.push_str("}\n\n");

    code.push_str("/// Get the dictionary for a language.\n");
    code.push_str("pub fn dictionary(language: Language) -> Arc<FstDictionary> {\n");
    code.push_str("    dictionary_for_language(language.family())\n");
    code.push_str("}\n\n");

    // PARSERS
    code.push_str("/// Get a parser for the given language ID and language.\n");
    code.push_str("pub fn parser_for_prose(\n");
    code.push_str("    language_id: &str,\n");
    code.push_str("    language: Language,\n");
    code.push_str("    markdown_options: MarkdownOptions,\n");
    code.push_str(") -> Option<Box<dyn Parser>> {\n");
    code.push_str("    match (language_id, prose_language(&language)) {\n");
    
    // Mail format parsers
    for lang in languages {
        if lang.dir_name == "english" {
            code.push_str("        (\"mail\", ProseLanguage::English) => Some(Box::new(EnglishModule::plain_parser())),\n");
        } else {
            if let Some(feature) = &lang.feature {
                code.push_str(&format!("        #[cfg(feature = \"{}\")]\n", feature));
            }
            code.push_str(&format!("        (\"mail\", ProseLanguage::{0}) => Some(Box::new({1}Module::plain_parser())),\n", lang.name, lang.name));
        }
    }
    code.push('\n');
    code.push_str("        // Markdown/Quarto format\n");
    
    // Markdown parsers for non-English languages
    for lang in languages {
        if lang.dir_name == "english" {
            continue;
        }
        
        if let Some(feature) = &lang.feature {
            code.push_str(&format!("        #[cfg(feature = \"{}\")]\n", feature));
        }
        code.push_str(&format!("        (\"markdown\" | \"quarto\", ProseLanguage::{0}) => Some(Box::new(\n", lang.name));
        code.push_str("            Markdown::with_inline_parser(markdown_options, |source| {\n");
        code.push_str(&format!("                {}Module::plain_parser().parse(source)\n", lang.name));
        code.push_str("            }),\n");
        code.push_str("        )),\n");
    }
    code.push_str("        (\"markdown\" | \"quarto\", _) => Some(Box::new(Markdown::new(markdown_options))),\n");
    code.push('\n');
    code.push_str("        // Org mode format\n");
    
    // Org mode parsers for non-English languages
    for lang in languages {
        if lang.dir_name == "english" {
            continue;
        }
        
        if let Some(feature) = &lang.feature {
            code.push_str(&format!("        #[cfg(feature = \"{}\")]\n", feature));
        }
        code.push_str(&format!("        (\"org\", ProseLanguage::{0}) => Some(Box::new(OrgMode::with_inline_parser(|source| {{\n", lang.name));
        code.push_str(&format!("            {}Module::plain_parser().parse(source)\n", lang.name));
        code.push_str("        }))),\n");
    }
    code.push_str("        (\"org\", _) => Some(Box::new(OrgMode::default())),\n");
    code.push('\n');
    code.push_str("        // Plain text format\n");
    
    // Plain text parsers
    for lang in languages {
        if let Some(feature) = &lang.feature {
            code.push_str(&format!("        #[cfg(feature = \"{}\")]\n", feature));
        }
        code.push_str(&format!("        (\"plaintext\" | \"text\", ProseLanguage::{0}) => {{\n", lang.name));
        code.push_str(&format!("            Some(Box::new({}Module::plain_parser()))\n", lang.name));
        code.push_str("        }\n");
    }
    code.push_str("        _ => None,\n");
    code.push_str("    }\n");
    code.push_str("}\n\n");

    // LINTERS
    code.push_str("/// Add language-specific linters to the lint group.\n");
    code.push_str("pub fn add_language_specific_linters(\n");
    code.push_str("    out: &mut LintGroup,\n");
    code.push_str("    language: Language,\n");
    code.push_str("    dictionary: Arc<impl Dictionary + 'static>,\n");
    code.push_str(") {\n");
    code.push_str("    match language {\n");
    
    for lang in languages {
        if lang.dir_name == "english" {
            code.push_str("        Language::English(_dialect) => {\n");
            code.push_str("            let lang_group = EnglishModule::rust_lint_group(dictionary);\n");
            code.push_str("            out.merge_from(lang_group);\n");
            code.push_str("        }\n");
        } else {
            if let Some(feature) = &lang.feature {
                code.push_str(&format!("        #[cfg(feature = \"{}\")]\n", feature));
            }
            code.push_str(&format!("        Language::{}(_) => {{\n", lang.name));
            code.push_str(&format!("            let lang_group = {}Module::rust_lint_group(dictionary);\n", lang.name));
            code.push_str("            out.merge_from(lang_group);\n");
            code.push_str("        }\n");
        }
    }
    code.push_str("    }\n");
    code.push_str("}\n\n");

    // WIR RULES
    code.push_str("/// Get the Weir rule lint group for a specific language.\n");
    code.push_str("pub fn weir_rules_lint_group(language: Language) -> LintGroup {\n");
    code.push_str("    match language {\n");
    
    for lang in languages {
        if lang.dir_name == "english" {
            code.push_str("        Language::English(_) => EnglishModule::weir_lint_group(),\n");
        } else {
            if let Some(feature) = &lang.feature {
                code.push_str(&format!("        #[cfg(feature = \"{}\")]\n", feature));
            }
            code.push_str(&format!("        Language::{}(_) => {}Module::weir_lint_group(),\n", lang.name, lang.name));
        }
    }
    code.push_str("    }\n");
    code.push_str("}\n\n");

    // CURATED LINT GROUPS
    code.push_str("/// Create a new curated lint group for a specific language with a custom dictionary.\n");
    code.push_str("pub fn new_curated_for_language(\n");
    code.push_str("    _dictionary: Arc<impl Dictionary + 'static>,\n");
    code.push_str("    language: Language,\n");
    code.push_str(") -> LintGroup {\n");
    code.push_str("    use crate::language::module::LanguageModule;\n\n");

    code.push_str("    match language {\n");
    
    for lang in languages {
        if lang.dir_name == "english" {
            code.push_str("        Language::English(_dialect) => {\n");
            code.push_str("            #[allow(clippy::let_and_return)]\n");
            code.push_str("            let group = EnglishModule::curated_lint_group(_dialect);\n");
            code.push_str("            group\n");
            code.push_str("        }\n");
        } else {
            if let Some(feature) = &lang.feature {
                code.push_str(&format!("        #[cfg(feature = \"{}\")]\n", feature));
            }
            code.push_str(&format!("        Language::{}(dialect) => {{\n", lang.name));
            code.push_str(&format!("            use crate::language::{}::module::{}Module;\n\n", lang.dir_name, lang.name));
            code.push_str(&format!("            let group = {}Module::curated_lint_group(dialect);\n", lang.name));
            code.push_str("            group\n");
            code.push_str("        }\n");
        }
    }
    code.push_str("    }\n");
    code.push_str("}\n");

    let dest = src_dir.join("registry.rs");
    fs::write(&dest, code).unwrap();

    // Generate dialect flags
    generate_dialect_flags_file(&src_dir, languages);
}

/// Generate dialect_flags.rs with dynamic dialect flags collection
fn generate_dialect_flags_file(src_dir: &Path, _languages: &[LanguageConfig]) {
    let manifest_dir = Path::new(env!("CARGO_MANIFEST_DIR"));

    let languages = discover_languages(manifest_dir);
    let mut code = String::new();

    // Header
    code.push_str("// Auto-generated by build.rs - do not edit manually\n");
    code.push_str(
        "// This file provides a centralized DialectFlags struct for all supported languages.\n",
    );
    code.push_str(
        "// Language-specific dialect flags are defined in each language's dialects.rs file.\n\n",
    );

    // Imports
    code.push_str("use serde::ser::SerializeStruct;\n");
    code.push_str("use serde::{Deserialize, Serialize};\n");
    code.push_str("use serde_json::Value;\n\n");

    // Import dialect types - these come from individual language modules
    code.push_str("#[allow(unused_imports)]\n");
    code.push_str("use crate::language::dialects::dialect_trait::DialectFlags as _;\n");

    // Add imports for each language
    for lang in &languages {
        if let Some(feature) = &lang.feature {
            code.push_str(&format!("#[cfg(feature = \"{}\")]\n", feature));
        }
        code.push_str(&format!(
            "use crate::language::{}::dialects::{{{}, {}}};\n",
            lang.dir_name, lang.dialect_module, lang.flags_module
        ));
        if lang.feature.is_none() {
            code.push('\n');
        }
    }

    code.push('\n');

    // Main DialectFlags struct
    code.push_str(
        "/// This represents a collection of dialect flags for all supported languages.\n",
    );
    code.push_str("/// Each language has its own set of dialect flags.\n");
    code.push_str("#[derive(Debug, Clone, Copy, PartialEq, PartialOrd, Eq, Hash)]\n");
    code.push_str("pub struct DialectFlags {\n");

    // Add struct fields
    for lang in &languages {
        if let Some(feature) = &lang.feature {
            code.push_str(&format!("    #[cfg(feature = \"{}\")]\n", feature));
        }
        code.push_str(&format!(
            "    pub {}: {},\n",
            lang.dir_name.to_lowercase(),
            lang.flags_module
        ));
    }

    code.push_str("}\n\n");

    // Serialize implementation - this delegates to individual language serialization via their Serialize derives
    code.push_str("impl Serialize for DialectFlags {\n");
    code.push_str("    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>\n");
    code.push_str("    where\n");
    code.push_str("        S: serde::Serializer,\n");
    code.push_str("    {\n");
    code.push_str("        let mut scoped = serializer.serialize_struct(\"DialectFlags\", 4)?;\n");
    
    // Generate serialize fields dynamically
    for lang in &languages {
        if let Some(feature) = &lang.feature {
            code.push_str(&format!("        #[cfg(feature = \"{}\")]\n", feature));
        }
        code.push_str(&format!("        scoped.serialize_field(\"{}\", &self.{})?;\n", lang.dir_name.to_lowercase(), lang.dir_name.to_lowercase()));
    }
    code.push_str("        scoped.end()\n");
    code.push_str("    }\n");
    code.push_str("}\n\n");

    // This is where it gets complex - the Deserialize implementation
    // The current implementation uses a ScopedDialectFlagsSerde helper
    code.push_str("impl<'de> Deserialize<'de> for DialectFlags {\n");
    code.push_str("    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>\n");
    code.push_str("    where\n");
    code.push_str("        D: serde::Deserializer<'de>,\n");
    code.push_str("    {\n");
    code.push_str(
        "        // Only accept the new scoped, language-specific dialect flags format.\n",
    );
    code.push_str("        let scoped = ScopedDialectFlagsSerde::deserialize(deserializer)?;\n");
    code.push_str("        Ok(scoped.into())\n");
    code.push_str("    }\n");
    code.push_str("}\n\n");

    // From implementation
    code.push_str("impl From<ScopedDialectFlagsSerde> for DialectFlags {\n");
    code.push_str("    fn from(value: ScopedDialectFlagsSerde) -> Self {\n");
    code.push_str("        Self {\n");
    
    for lang in &languages {
        if let Some(feature) = &lang.feature {
            code.push_str(&format!("            #[cfg(feature = \"{}\")]\n", feature));
            code.push_str(&format!("            {}: value.{},\n", lang.dir_name.to_lowercase(), lang.dir_name.to_lowercase()));
        } else {
            code.push_str(&format!("            {}: value.{},", lang.dir_name.to_lowercase(), lang.dir_name.to_lowercase()));
            if lang.dir_name != "slovak" {
                code.push_str("\n");
            }
        }
    }
    code.push_str("        }\n");
    code.push_str("    }\n");
    code.push_str("}\n\n");

    // empty() method
    code.push_str("impl DialectFlags {\n");
    code.push_str("    #[must_use]\n");
    code.push_str("    pub const fn empty() -> Self {\n");
    code.push_str("        Self {\n");
    
    for lang in &languages {
        if let Some(feature) = &lang.feature {
            code.push_str(&format!("            #[cfg(feature = \"{}\")]\n", feature));
            code.push_str(&format!("            {}: {}::empty(),\n", lang.dir_name.to_lowercase(), lang.flags_module));
        } else {
            code.push_str(&format!("            {}: {}::empty(),", lang.dir_name.to_lowercase(), lang.flags_module));
            if lang.dir_name != "slovak" {
                code.push_str("\n");
            }
        }
    }
    code.push_str("        }\n");
    code.push_str("    }\n\n");

    // new() method
    code.push_str("    /// Creates a DialectFlags with the specified dialect flags.\n");
    code.push_str("    #[must_use]\n");
    code.push_str("    pub const fn new(\n");
    
    // Generate parameters dynamically
    for (i, lang) in languages.iter().enumerate() {
        if i == 0 {
            code.push_str("        english: EnglishDialectFlags,\n");
        } else {
            if let Some(feature) = &lang.feature {
                code.push_str(&format!("        #[cfg(feature = \"{}\")] {}: {},\n", feature, lang.dir_name.to_lowercase(), lang.flags_module));
            } else {
                code.push_str(&format!("        {}: {},\n", lang.dir_name.to_lowercase(), lang.flags_module));
            }
        }
    }
    code.push_str("    ) -> Self {\n");
    code.push_str("        Self {\n");
    
    for lang in &languages {
        if let Some(feature) = &lang.feature {
            code.push_str(&format!("            #[cfg(feature = \"{}\")]\n", feature));
            code.push_str(&format!("            {},\n", lang.dir_name.to_lowercase()));
        } else {
            code.push_str(&format!("            {},", lang.dir_name.to_lowercase()));
            if lang.dir_name != "slovak" {
                code.push_str("\n");
            }
        }
    }
    code.push_str("        }\n");
    code.push_str("    }\n\n");

    // from_english_dialect() method
    code.push_str(
        "    /// Creates a DialectFlags with only the specified English dialect enabled.\n",
    );
    code.push_str("    /// This is a convenience method for tests and cases where only English dialects are needed.\n");
    code.push_str("    #[must_use]\n");
    code.push_str("    pub fn from_english_dialect(dialect: EnglishDialect) -> Self {\n");
    code.push_str("        let english_flags = match dialect {\n");
    code.push_str("            EnglishDialect::American => EnglishDialectFlags::AMERICAN,\n");
    code.push_str("            EnglishDialect::Canadian => EnglishDialectFlags::CANADIAN,\n");
    code.push_str("            EnglishDialect::Australian => EnglishDialectFlags::AUSTRALIAN,\n");
    code.push_str("            EnglishDialect::British => EnglishDialectFlags::BRITISH,\n");
    code.push_str("            EnglishDialect::Indian => EnglishDialectFlags::INDIAN,\n");
    code.push_str("        };\n\n");

    code.push_str("        Self {\n");
    code.push_str("            english: english_flags,\n");
    
    for lang in &languages {
        if lang.dir_name == "english" {
            continue;
        }
        if let Some(feature) = &lang.feature {
            code.push_str(&format!("            #[cfg(feature = \"{}\")]\n", feature));
            code.push_str(&format!("            {}: {}::empty(),\n", lang.dir_name.to_lowercase(), lang.flags_module));
        } else {
            code.push_str(&format!("            {}: {}::empty(),", lang.dir_name.to_lowercase(), lang.flags_module));
            if lang.dir_name != "slovak" {
                code.push_str("\n");
            }
        }
    }
    code.push_str("        }\n");
    code.push_str("    }\n\n");

    // is_empty() method
    code.push_str("    #[must_use]\n");
    code.push_str("    #[allow(unused_mut)]\n");
    code.push_str("    pub fn is_empty(self) -> bool {\n");
    code.push_str("        let mut result = self.english.is_empty();\n");
    
    for lang in &languages {
        if lang.dir_name == "english" {
            continue;
        }
        if let Some(feature) = &lang.feature {
            code.push_str(&format!("        #[cfg(feature = \"{}\")]\n", feature));
            code.push_str("        {\n");
            code.push_str(&format!("            result = result && self.{}.is_empty();\n", lang.dir_name.to_lowercase()));
            code.push_str("        }\n");
        }
    }
    code.push_str("        result\n");
    code.push_str("    }\n\n");

    // English dialect helper methods
    code.push_str("    #[must_use]\n");
    code.push_str(
        "    pub fn is_english_dialect_enabled(self, dialect: EnglishDialect) -> bool {\n",
    );
    code.push_str("        self.english.is_dialect_enabled(dialect)\n");
    code.push_str("    }\n\n");

    code.push_str("    #[must_use]\n");
    code.push_str(
        "    pub fn is_english_dialect_enabled_strict(self, dialect: EnglishDialect) -> bool {\n",
    );
    code.push_str("        self.english.is_dialect_enabled_strict(dialect)\n");
    code.push_str("    }\n\n");

    // Non-English dialect helper methods
    for lang in &languages {
        if lang.dir_name == "english" {
            continue;
        }
        
        if let Some(feature) = &lang.feature {
            code.push_str(&format!("    #[cfg(feature = \"{}\")]\n", feature));
        }
        code.push_str("    #[must_use]\n");
        code.push_str(&format!("    pub fn is_{}_dialect_enabled(self, dialect: {}Dialect) -> bool {{\n", lang.dir_name.to_lowercase(), lang.name));
        code.push_str(&format!("        self.{}.is_dialect_enabled(dialect)\n", lang.dir_name.to_lowercase()));
        code.push_str("    }\n\n");

        if let Some(feature) = &lang.feature {
            code.push_str(&format!("    #[cfg(feature = \"{}\")]\n", feature));
        }
        code.push_str("    #[must_use]\n");
        code.push_str(&format!("    pub fn is_{}_dialect_enabled_strict(self, dialect: {}Dialect) -> bool {{\n", lang.dir_name.to_lowercase(), lang.name));
        code.push_str(&format!("        self.{}.is_dialect_enabled_strict(dialect)\n", lang.dir_name.to_lowercase()));
        code.push_str("    }\n\n");
    }

    // get_most_used_dialects_from_document method
    code.push_str("    /// Gets the most commonly used dialect(s) in the document.\n");
    code.push_str("    ///\n");
    code.push_str(
        "    /// If multiple dialects are used equally often, they will all be enabled in the returned\n",
    );
    code.push_str("    /// `DialectFlags`. On the other hand, if there is a single dialect that is used the most, it\n");
    code.push_str("    /// will be the only one enabled.\n");
    code.push_str("    #[must_use]\n");
    code.push_str(
        "    pub fn get_most_used_dialects_from_document(document: &crate::Document) -> Self {\n",
    );
    code.push_str("        // Get the most used dialects for each language separately\n");
    code.push_str("        let english_flags = EnglishDialectFlags::get_most_used_dialects_from_document(document);\n");
    
    for lang in &languages {
        if lang.dir_name == "english" {
            continue;
        }
        if let Some(feature) = &lang.feature {
            code.push_str(&format!("        #[cfg(feature = \"{}\")]\n", feature));
        }
        code.push_str(&format!("        let {}_flags = {}::get_most_used_dialects_from_document(document);\n", lang.dir_name.to_lowercase(), lang.flags_module));
    }

    code.push_str("\n        Self {\n");
    code.push_str("            english: english_flags,\n");
    
    for lang in &languages {
        if lang.dir_name == "english" {
            continue;
        }
        if let Some(feature) = &lang.feature {
            code.push_str(&format!("            #[cfg(feature = \"{}\")]\n", feature));
            code.push_str(&format!("            {}: {}_flags,\n", lang.dir_name.to_lowercase(), lang.dir_name.to_lowercase()));
        } else {
            code.push_str(&format!("            {}: {}_flags,", lang.dir_name.to_lowercase(), lang.dir_name.to_lowercase()));
            if lang.dir_name != "slovak" {
                code.push_str("\n");
            }
        }
    }
    code.push_str("        }\n");
    code.push_str("    }\n");

    // BitOr implementation
    code.push_str("}\n");
    code.push_str("impl std::ops::BitOr for DialectFlags {\n");
    code.push_str("    type Output = Self;\n\n");

    code.push_str("    fn bitor(self, rhs: Self) -> Self::Output {\n");
    code.push_str("        Self {\n");
    
    for lang in &languages {
        if let Some(feature) = &lang.feature {
            code.push_str(&format!("            #[cfg(feature = \"{}\")]\n", feature));
        }
        code.push_str(&format!("            {}: self.{} | rhs.{},", lang.dir_name.to_lowercase(), lang.dir_name.to_lowercase(), lang.dir_name.to_lowercase()));
        code.push_str("\n");
    }
    code.push_str("        }\n");
    code.push_str("    }\n");
    code.push_str("}\n\n");

    // BitOrAssign implementation
    code.push_str("impl std::ops::BitOrAssign for DialectFlags {\n");
    code.push_str("    fn bitor_assign(&mut self, rhs: Self) {\n");
    code.push_str("        self.english |= rhs.english;\n");
    
    for lang in &languages {
        if lang.dir_name == "english" {
            continue;
        }
        if let Some(feature) = &lang.feature {
            code.push_str(&format!("        #[cfg(feature = \"{}\")]\n", feature));
            code.push_str("        {\n");
            code.push_str(&format!("            self.{} |= rhs.{};\n", lang.dir_name.to_lowercase(), lang.dir_name.to_lowercase()));
            code.push_str("        }\n");
        }
    }
    code.push_str("    }\n");
    code.push_str("}\n\n");

    // Default implementation
    code.push_str("impl Default for DialectFlags {\n");
    code.push_str("    /// A default value with no dialects explicitly enabled.\n");
    code.push_str("    /// Implicitly, this state corresponds to all dialects being enabled.\n");
    code.push_str("    fn default() -> Self {\n");
    code.push_str("        Self::empty()\n");
    code.push_str("    }\n");
    code.push_str("}\n\n");

    // ScopedDialectFlagsSerde for deserialization
    code.push_str(
        "// Use the ScopedDialectFlagsSerde and DialectFlags (language-scoped) for serialization/deserialization.\n",
    );
    code.push_str("#[derive(Debug, Clone, Copy, PartialEq, PartialOrd, Eq, Hash, Default)]\n");
    code.push_str("struct ScopedDialectFlagsSerde {\n");
    
    for lang in &languages {
        if let Some(feature) = &lang.feature {
            code.push_str(&format!("    #[cfg(feature = \"{}\")]\n", feature));
            code.push_str(&format!("    {}: {},\n", lang.dir_name.to_lowercase(), lang.flags_module));
        } else {
            code.push_str(&format!("    {}: {},", lang.dir_name.to_lowercase(), lang.flags_module));
            if lang.dir_name != "slovak" {
                code.push_str("\n");
            }
        }
    }
    code.push_str("}\n\n");

    // Deserialize implementation for ScopedDialectFlagsSerde
    code.push_str("impl<'de> Deserialize<'de> for ScopedDialectFlagsSerde {\n");
    code.push_str("    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>\n");
    code.push_str("    where\n");
    code.push_str("        D: serde::Deserializer<'de>,\n");
    code.push_str("    {\n");
    code.push_str("        use serde::de::{Error, Unexpected};\n\n");

    code.push_str("        let value = Value::deserialize(deserializer)?;\n\n");

    code.push_str("        match value {\n");
    code.push_str("            Value::Object(map) => {\n");
    code.push_str("                let mut english = EnglishDialectFlags::default();\n");

    // Generate variable declarations for each language's flags
    for lang in &languages {
        if lang.dir_name == "english" {
            continue;
        }
        if let Some(feature) = &lang.feature {
            code.push_str(&format!("                #[cfg(feature = \"{}\")]\n", feature));
        }
        code.push_str(&format!("                let mut {} = {}::default();\n", lang.dir_name.to_lowercase(), lang.flags_module));
    }
    
    code.push_str("\n");

    code.push_str("                for (key, val) in map {\n");
    code.push_str("                    match key.as_str() {\n");
    
    // English deserialization
    code.push_str("                        \"english\" => {\n");
    code.push_str("                            english = match val {\n");
    code.push_str("                                Value::String(s) => match s.as_str() {\n");
    code.push_str(
        "                                    \"AMERICAN\" => Ok(EnglishDialectFlags::AMERICAN),\n",
    );
    code.push_str(
        "                                    \"CANADIAN\" => Ok(EnglishDialectFlags::CANADIAN),\n",
    );
    code.push_str("                                    \"AUSTRALIAN\" => Ok(EnglishDialectFlags::AUSTRALIAN),\n");
    code.push_str(
        "                                    \"BRITISH\" => Ok(EnglishDialectFlags::BRITISH),\n",
    );
    code.push_str(
        "                                    \"INDIAN\" => Ok(EnglishDialectFlags::INDIAN),\n",
    );
    code.push_str("                                    _ => {\n");
    code.push_str("                                        Err(Error::custom(format!(\"Unknown English dialect: {s}\")))\n");
    code.push_str("                                    }\n");
    code.push_str("                                },\n");
    code.push_str("                                _ => Err(Error::invalid_type(\n");
    code.push_str("                                    Unexpected::Other(\"english\"),\n");
    code.push_str("                                    &\"string\",\n");
    code.push_str("                                )),\n");
    code.push_str("                            }?;\n");
    code.push_str("                        }\n");

    // Non-English language deserialization
    for lang in &languages {
        if lang.dir_name == "english" {
            continue;
        }
        
        if let Some(feature) = &lang.feature {
            code.push_str(&format!("                        #[cfg(feature = \"{}\")]\n", feature));
        }
        code.push_str(&format!("                        \"{}\" => {{\n", lang.dir_name.to_lowercase()));
        code.push_str(&format!("                            {} = match val {{\n", lang.dir_name.to_lowercase()));
        code.push_str("                                Value::String(s) => match s.as_str() {\n");
        
        // Generate dialect variant match arms
        // This is hardcoded per language for now
        if lang.dir_name == "german" {
            code.push_str("                                    \"STANDARD\" => Ok(GermanDialectFlags::STANDARD),\n");
            code.push_str("                                    \"AUSTRIAN\" => Ok(GermanDialectFlags::AUSTRIAN),\n");
            code.push_str("                                    \"SWISS\" => Ok(GermanDialectFlags::SWISS),\n");
            code.push_str("                                    _ => Err(Error::custom(format!(\"Unknown German dialect: {s}\"))),\n");
        } else if lang.dir_name == "portuguese" {
            code.push_str("                                    \"EUROPEAN\" => Ok(PortugueseDialectFlags::EUROPEAN),\n");
            code.push_str("                                    \"BRAZILIAN\" => Ok(PortugueseDialectFlags::BRAZILIAN),\n");
            code.push_str("                                    \"AFRICAN\" => Ok(PortugueseDialectFlags::AFRICAN),\n");
            code.push_str("                                    _ => Err(Error::custom(format!(\n");
            code.push_str("                                        \"Unknown Portuguese dialect: {s}\"\n");
            code.push_str("                                    ))),\n");
        } else if lang.dir_name == "slovak" {
            code.push_str("                                    \"STANDARD\" => Ok(SlovakDialectFlags::STANDARD),\n");
            code.push_str("                                    _ => Err(Error::custom(format!(\"Unknown Slovak dialect: {s}\"))),\n");
        }
        
        code.push_str("                                },\n");
        code.push_str("                                _ => {\n");
        code.push_str(&format!("                                    Err(Error::invalid_type(Unexpected::Other(\"{}\"), &\"string\"))\n", lang.dir_name.to_lowercase()));
        code.push_str("                                }\n");
        code.push_str("                            }?;\n");
        code.push_str("                        }\n");
    }
    code.push_str("                        _ => {\n");
    code.push_str(
        "                            // Build list of valid fields based on enabled features\n",
    );
    code.push_str("                            let valid_fields: Vec<&'static str> = {\n");
    code.push_str("                                #[allow(unused_mut)]\n");
    code.push_str("                                let mut fields = vec![\"english\"];\n");

    // Generate valid_fields list dynamically from discovered languages
    for lang in &languages {
        if lang.dir_name == "english" {
            continue; // English already added
        }
        if let Some(feature) = &lang.feature {
            code.push_str(&format!("                                #[cfg(feature = \"{}\")]\n", feature));
            code.push_str("                                {\n");
            code.push_str(&format!("                                    fields.push(\"{}\");\n", lang.dir_name.to_lowercase()));
            code.push_str("                                }\n");
        }
    }

    code.push_str("                                fields\n");
    code.push_str("                            };");
    code.push_str(
        "                            // Convert to a static slice by leaking the memory\n",
    );
    code.push_str("                            // This is safe as it's only done during deserialization error handling\n");
    code.push_str(
        "                            let valid_fields_static: &'static [&'static str] =\n",
    );
    code.push_str("                                Box::leak(valid_fields.into_boxed_slice());\n");
    code.push_str("                            return Err(Error::unknown_field(&key, valid_fields_static));\n");
    code.push_str("                        }\n");
    code.push_str("                    }\n");
    code.push_str("                }\n");
    code.push_str("                Ok(ScopedDialectFlagsSerde {\n");
    code.push_str("                    english,\n");
    
    // Generate struct fields dynamically
    for lang in &languages {
        if lang.dir_name == "english" {
            continue; // English already added
        }
        if let Some(feature) = &lang.feature {
            code.push_str(&format!("                    #[cfg(feature = \"{}\")]\n", feature));
            code.push_str(&format!("                    {},\n", lang.dir_name.to_lowercase()));
        }
    }
    
    code.push_str("                })\n");
    code.push_str("            }\n");
    code.push_str("            Value::String(s) => Err(Error::custom(format!(\n");
    code.push_str(
        "                \"Legacy flat string format for dialect flags is no longer supported: {s}\"\n",
    );
    code.push_str("            ))),\n");
    code.push_str("            _ => Err(Error::custom(\"Expected object for dialect flags\")),\n");
    code.push_str("        }\n");
    code.push_str("    }\n");
    code.push_str("}\n");
    // Write the generated file
    let dest = src_dir.join("dialects").join("dialect_flags.rs");
    fs::create_dir_all(dest.parent().unwrap()).unwrap();
    fs::write(&dest, code).unwrap();

    println!("cargo:rerun-if-changed=src/language/dialects/dialect_flags.rs");
}