use std::{fs, path::Path};

#[derive(Debug)]
pub struct StandaloneRule {
    pub name: String,
    pub relative_path: String,
}

#[derive(Debug)]
pub struct GroupedRule {
    pub public_name: String,
    pub children: Vec<StandaloneRule>,
}

/// Convert a Weir rule path to an `include_str!`-friendly relative path.
pub fn path_as_weir_relative(path: &Path, root: &Path) -> String {
    path.strip_prefix(root)
        .unwrap()
        .to_string_lossy()
        .replace('\\', "/")
}

/// Top-level `RuleName.weir` files are public as `RuleName`.
pub fn rule_name_from_path(path: &Path) -> String {
    path.file_stem().unwrap().to_string_lossy().to_string()
}

/// Grouped child rules use their relative path as a private name.
pub fn rule_name_from_relative_path(path: &Path, root: &Path) -> String {
    let mut relative = path_as_weir_relative(path, root);
    relative.truncate(relative.len() - ".weir".len());
    relative
}

/// Recursively collect child `.weir` files for a grouped rule directory.
pub fn collect_weir_files(dir: &Path, group_root: &Path, weir_root: &Path) -> Vec<StandaloneRule> {
    println!("cargo:rerun-if-changed={}", dir.display());

    let mut entries = fs::read_dir(dir)
        .unwrap()
        .filter_map(Result::ok)
        .collect::<Vec<_>>();

    entries.sort_by_key(|entry| entry.path());

    let mut rules = Vec::new();

    for entry in entries {
        let path = entry.path();
        let file_type = entry.file_type().unwrap();

        if file_type.is_dir() {
            rules.extend(collect_weir_files(&path, group_root, weir_root));
        } else if file_type.is_file() && path.extension().is_some_and(|ext| ext == "weir") {
            println!("cargo:rerun-if-changed={}", path.display());

            rules.push(StandaloneRule {
                name: rule_name_from_relative_path(&path, group_root),
                relative_path: path_as_weir_relative(&path, weir_root),
            });
        }
    }

    rules
}

/// Render a string as an escaped Rust string literal for generated source.
pub fn rust_string_literal(value: &str) -> String {
    format!("{value:?}")
}

pub fn write_grouped_weir_boilerplate(weir_rule_dir: &Path, dest: &Path) {
    let mut entries = fs::read_dir(weir_rule_dir)
        .unwrap()
        .filter_map(Result::ok)
        .collect::<Vec<_>>();

    entries.sort_by_key(|entry| entry.path());

    let mut standalone_rules = Vec::new();
    let mut grouped_rules = Vec::new();

    // Watch the root for top-level `.weir` files and group directories.
    println!("cargo:rerun-if-changed={}", weir_rule_dir.display());

    for entry in entries {
        let path = entry.path();
        let file_type = entry.file_type().unwrap();

        if file_type.is_dir() {
            let public_name = entry.file_name().to_string_lossy().to_string();
            let children = collect_weir_files(&path, &path, weir_rule_dir);

            if !children.is_empty() {
                grouped_rules.push(GroupedRule {
                    public_name,
                    children,
                });
            }
        } else if file_type.is_file() && path.extension().is_some_and(|ext| ext == "weir") {
            println!("cargo:rerun-if-changed={}", path.display());

            standalone_rules.push(StandaloneRule {
                name: rule_name_from_path(&path),
                relative_path: path_as_weir_relative(&path, weir_rule_dir),
            });
        }
    }

    let mut code = String::new();

    // Add header comment
    code.push_str("// Auto-generated by build.rs - do not edit manually\n");
    code.push_str("// Weir rule registration for Harper grammar checking\n");
    code.push_str("// Generated from .weir files in the source directory\n\n");

    code.push_str("generate_boilerplate! {\n");
    code.push_str("    standalone: [\n");
    for rule in standalone_rules {
        code.push_str(&format!(
            "        ({}, {}),\n",
            rust_string_literal(&rule.name),
            rust_string_literal(&rule.relative_path)
        ));
    }
    code.push_str("    ],\n");

    code.push_str("    groups: [\n");
    for group in grouped_rules {
        code.push_str(&format!(
            "        ({}, [\n",
            rust_string_literal(&group.public_name)
        ));

        for child in group.children {
            code.push_str(&format!(
                "            ({}, {}),\n",
                rust_string_literal(&child.name),
                rust_string_literal(&child.relative_path)
            ));
        }

        code.push_str("        ]),\n");
    }
    code.push_str("    ],\n");
    code.push_str("}\n");

    // Ensure the parent directory exists
    if let Some(parent) = dest.parent() {
        fs::create_dir_all(parent).unwrap();
    }
    fs::write(dest, code).unwrap();
}

/// Write the whole `weir_rules` module for one language.
///
/// Each language used to carry its own ~50-line copy of an identical macro that
/// differed only in an environment variable name. Now its `mod.rs` is a single
/// `include!` and everything below is generated from the `.weir` files that are
/// actually there, tests included.
///
/// English keeps [`write_grouped_weir_boilerplate`]: its rules nest into groups,
/// which this flat form does not express.
pub fn write_flat_weir_module(weir_rule_dir: &Path, dest: &Path, language: &str) {
    let mut files = match fs::read_dir(weir_rule_dir) {
        Ok(entries) => entries
            .filter_map(Result::ok)
            .map(|entry| entry.path())
            .filter(|path| path.is_file() && path.extension().is_some_and(|ext| ext == "weir"))
            .collect::<Vec<_>>(),
        Err(_) => Vec::new(),
    };

    files.sort();

    let names: Vec<String> = files
        .iter()
        .map(|file| {
            println!("cargo:rerun-if-changed={}", file.display());
            file.file_stem().unwrap().to_string_lossy().to_string()
        })
        .collect();

    // `include_str!` needs a literal, so the rule directory arrives as an
    // environment variable the build script sets alongside this file.
    let source_of = |name: &str| {
        format!("include_str!(concat!(env!(\"{language}_WEIR_RULE_DIR\"), \"/{name}.weir\"))")
    };

    let mut code = String::new();
    code.push_str("// Auto-generated by build.rs - do not edit manually\n");
    code.push_str("// Weir rule module, generated from the .weir files in this directory.\n\n");
    code.push_str("use crate::linting::LintGroup;\n");
    if !names.is_empty() {
        code.push_str("use crate::weir::WeirLinter;\n");
    }

    code.push_str("\n/// Every Weir rule this language defines, all enabled.\n");
    code.push_str("pub fn lint_group() -> LintGroup {\n");
    code.push_str("    #[allow(unused_mut)]\n");
    code.push_str("    let mut group = LintGroup::default();\n\n");

    for name in &names {
        code.push_str(&format!(
            "    let linter = WeirLinter::new({}).unwrap();\n",
            source_of(name)
        ));
        code.push_str("    match linter.into_sentence_linter() {\n");
        code.push_str(&format!(
            "        Ok(linter) => group.add_sentence_expr_linter(\"{name}\", linter),\n"
        ));
        code.push_str(&format!(
            "        Err(linter) => group.add_chunk_expr_linter(\n            \"{name}\",\n            linter.into_chunk_linter().unwrap_or_else(|_| unreachable!()),\n        ),\n"
        ));
        code.push_str("    };\n\n");
    }

    code.push_str("    group.set_all_rules_to(Some(true));\n");
    code.push_str("    group\n");
    code.push_str("}\n");

    if !names.is_empty() {
        code.push_str("\n#[cfg(test)]\nmod tests {\n");
        code.push_str("    use crate::weir::WeirLinter;\n");
        code.push_str("    use crate::weir::tests::assert_passes_all;\n");
        for name in &names {
            let snake = to_snake_case(name);
            code.push_str(&format!(
                "\n    /// The `test` and `allows` lines in {name}.weir.\n"
            ));
            code.push_str("    #[test]\n");
            code.push_str(&format!("    fn run_tests_for_{snake}() {{\n"));
            code.push_str(&format!(
                "        let mut linter = WeirLinter::new({}).unwrap();\n",
                source_of(name)
            ));
            code.push_str("        assert_passes_all(&mut linter);\n");
            code.push_str("    }\n");
        }
        code.push_str("}\n");
    }

    fs::write(dest, code).unwrap();
}

/// `ZumAnbeissen` -> `zum_anbeissen`, matching the names the old `paste!` macro
/// produced so test names do not churn.
fn to_snake_case(name: &str) -> String {
    let mut out = String::new();
    for (index, character) in name.chars().enumerate() {
        if character.is_uppercase() {
            if index != 0 {
                out.push('_');
            }
            out.extend(character.to_lowercase());
        } else {
            out.push(character);
        }
    }
    out
}

pub fn process_language_weir_rules(language_dir: &Path, out_dir: &Path) {
    if let Ok(language_entries) = fs::read_dir(language_dir) {
        for language_entry in language_entries.filter_map(Result::ok) {
            let language_path = language_entry.path();
            if !language_path.is_dir() {
                continue;
            }

            // Extract language name from directory
            let language_name = language_path
                .file_name()
                .and_then(|name| name.to_str())
                .map(|name| name.to_uppercase());

            if language_name.is_none() {
                continue;
            }

            let language_name = language_name.unwrap();
            let weir_rules_dir = language_path.join("linting/weir_rules");

            // Check if the weir_rules directory exists
            if !weir_rules_dir.exists() {
                continue;
            }

            // Load language configuration to check for weir rules subdirectory
            use crate::build_lib::language_config::load_language_config;

            let dir_name = language_path
                .file_name()
                .and_then(|name| name.to_str())
                .unwrap_or("");

            let final_weir_dir =
                if let Some(config) = load_language_config(&language_path, dir_name) {
                    // Use configured subdirectory if specified
                    if let Some(subdir) = &config.weir_rules_subdirectory {
                        weir_rules_dir.join(subdir)
                    } else {
                        weir_rules_dir
                    }
                } else {
                    // No config.toml? Skip this language for weir rules processing
                    // All languages must have a config.toml file
                    continue;
                };

            // Only process if the directory exists and contains .weir files
            if !final_weir_dir.exists() {
                continue;
            }

            // A language with no rules yet still gets a module, so its
            // `weir_lint_group()` compiles and returns an empty group.
            let lowercase_name = language_name.to_lowercase();
            let dest = out_dir.join(format!("{}_weir_rules_generated_list.rs", lowercase_name));

            write_flat_weir_module(&final_weir_dir, &dest, &language_name);

            println!(
                "cargo:rustc-env={}_WEIR_RULE_DIR={}",
                language_name,
                final_weir_dir.display()
            );
            println!(
                "cargo:rustc-env={}_WEIR_RULE_LIST={}",
                language_name,
                dest.display()
            );
        }
    }
}
