//! Harper Core Build Script
//!
//! This build script is the entry point for Harper's compile-time code generation system.
//! It uses the build_lib module which contains the main orchestration logic.
//!
//! ## Build System Structure
//!
//! - `build.rs`: This entry point file with documentation
//! - `build_lib/`: Build library modules:
//!   - `mod.rs`: Main orchestration logic
//!   - `language_config.rs`: Language discovery and configuration
//!   - `language_modules.rs`: Language integration code generation
//!   - `weir_rules.rs`: Weir rule processing
//!
//! ## What This Build Script Does
//!
//! 1. **Weir Rule Processing**: Compiles and prepares Weir grammar rules
//! 2. **Language Integration**: Generates code to integrate language modules
//! 3. **Feature-based Compilation**: Conditional compilation for optional languages
//!
//! The generated code enables Harper to support multiple languages while keeping
//! the main codebase clean and maintainable.
//!
//! ## Automatically Generated Files
//!
//! The following files are automatically generated and should not be edited manually:
//!
//! - `src/language/mod.rs` - Language module declarations and re-exports
//! - `src/language/languages.rs` - Language enum and parsing functions
//! - `src/language/registry.rs` - Language registry and integration code
//!
//! These files are generated by the build system and are written only when their
//! content changes. The build system formats them via the `rustfmt` binary.

mod build_lib;

fn main() {
    build_lib::run_build();
}
