[workspace]
members = [ "harper-cli", "harper-core", "harper-dictionary-parsing", "harper-ls", "harper-comments", "harper-wasm", "harper-tree-sitter", "harper-html", "harper-lib"]
resolver = "2"

[profile.release]
opt-level = 3
strip = true
