[workspace]
members = [ "harper-cli", "harper-core", "harper-ls", "harper-comments", "harper-wasm", "harper-tree-sitter", "harper-html", "harper-literate-haskell", "harper-typst" , "harper-stats"]
resolver = "2"

[profile.release]
codegen-units = 1
lto = true
opt-level = 3
strip = true
