# This Docker compose file is for development of the Harper website and web services.
# You do not need it to use Harper.

services:
  site:
    build:
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      - ORIGIN=http://localhost:3000
      - DATABASE_URL=mysql://devuser:password@db:3306/harper
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mariadb:lts
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: harper
      MARIADB_USER: devuser
      MARIADB_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
