packages:
  - packages/*
  - harper-wasm/pkg
  - packages/harper.js/examples/*
catalog:
  typescript: ^5.9.3
  tslib: ^2.8.1
  '@types/node': ^22.13.10
  '@babel/runtime': ^7.26.10
onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@parcel/watcher'
  - '@swc/core'
  - '@vscode/vsce-sign'
  - core-js
  - core-js-pure
  - esbuild
  - keytar
  - msw
  - svelte-preprocess
  - '@tailwindcss/oxide'
overrides:
  ws@>=8.0.0 <8.17.1: '>=8.17.1'
  body-parser@<1.20.3: '>=1.20.3'
  serve-static@<1.16.0: '>=1.16.0'
  express@<4.20.0: '>=4.20.0'
  path-to-regexp@<0.1.10: '>=0.1.10'
  esbuild@<=0.24.2: '>=0.25.0'
  vite@>=5.0.0 <5.4.18: '>=5.4.18'
  cookie@<0.7.0: '>=0.7.0'
  '@babel/runtime@<7.26.10': '>=7.26.10'
  http-proxy-middleware@>=1.3.0 <2.0.9: '>=2.0.9'
  http-proxy-middleware@>=1.3.0 <2.0.8: '>=2.0.8'
  vite@>=5.0.0 <=5.4.18: '>=5.4.19'
  path-to-regexp@<0.1.12: '>=0.1.12'
  brace-expansion@>=1.0.0 <=1.1.11: '>=1.1.12'
  brace-expansion@>=2.0.0 <=2.0.1: '>=2.0.2'
  on-headers@<1.1.0: '>=1.1.0'
  vite@<=5.4.19: '>=5.4.20'
  vite@>=6.0.0 <=6.3.5: '>=6.3.6'
  webpack-dev-server@<=5.2.0: '>=5.2.1'
  vite@>=5.2.6 <=5.4.20: '>=5.4.21'
  vite@>=6.0.0 <=6.4.0: '>=6.4.1'
  tar-fs@>=2.0.0 <2.1.4: '>=2.1.4'
  tar-fs@>=3.0.0 <3.1.1: '>=3.1.1'
  tmp@<=0.2.3: '>=0.2.4'
  form-data@>=4.0.0 <4.0.4: '>=4.0.4'
  tar-fs@>=3.0.0 <3.0.9: '>=3.0.9'
  tar-fs@>=2.0.0 <2.1.3: '>=2.1.3'
  send@<0.19.0: '>=0.19.0'
  min-document@<=2.19.0: '>=2.19.1'
  js-yaml@<3.14.2: '>=3.14.2'
  js-yaml@>=4.0.0 <4.1.1: '>=4.1.1'
  glob@>=10.2.0 <10.5.0: '>=10.5.0'
  glob@>=11.0.0 <11.1.0: '>=11.1.0'
  node-forge@<1.3.2: '>=1.3.2'
  mdast-util-to-hast@>=13.0.0 <13.2.1: '>=13.2.1'
  jws@=4.0.0: '>=4.0.1'
  jws@<3.2.3: '>=3.2.3'
  qs@<6.14.1: '>=6.14.1'
  devalue@>=5.1.0 <5.6.2: '>=5.6.2'
  devalue@>=5.3.0 <=5.6.1: '>=5.6.2'
  '@sveltejs/kit@>=2.19.0 <=2.49.4': '>=2.49.5'
  axios@>=1.0.0 <1.12.0: '>=1.12.0'
  lodash-es@>=4.0.0 <=4.17.22: '>=4.17.23'
  lodash@>=4.0.0 <=4.17.22: '>=4.17.23'
  diff@<4.0.4: '>=4.0.4'
  diff@>=6.0.0 <8.0.3: '>=8.0.3'
  undici@<6.23.0: '>=6.23.0'
