// Auto-generated by harper-core build.rs - do not edit manually
//! This file provides the Dialect enum for harper-wasm.
//! It is auto-generated from harper-core's language configurations
//! to ensure all languages are automatically supported.

/// Specifies a dialect, often used for linting.
#[wasm_bindgen]
#[derive(Serialize, Deserialize, Debug, Clone, Copy)]
pub enum Dialect {
    // English dialects
    American,
    British,
    Australian,
    Canadian,
    Indian,
    // German dialects
    GermanStandard,
    GermanAustrian,
    GermanSwiss,
    // Portuguese dialects
    PortuguesePT,
    PortugueseBR,
    PortugueseAO,
    // Slovak dialects
    SlovakStandard,
}
