use hashbrown::HashMap;
use serde::{Deserialize, Serialize};
use smallvec::ToSmallVec;

use super::super::word_map::{WordMap, WordMapEntry};
use super::Error;
use super::affix_replacement::AffixReplacement;
use super::expansion::Property;
use super::expansion::{
    AffixEntryKind,
    AffixEntryKind::{Prefix, Suffix},
    Expansion, HumanReadableExpansion,
};
use super::word_list::AnnotatedWord;
use crate::dict_word_metadata_orthography::OrthFlags;
use crate::spell::WordId;
use crate::{CharString, DictWordMetadata, Span};

#[derive(Debug, Clone)]
pub struct AttributeList {
    /// Key = Affix Flag
    affixes: HashMap<char, Expansion>,
    properties: HashMap<char, Property>,
}

/// Describes how a word was generated during dictionary expansion.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ProvenanceKind {
    /// The word appears directly in `dictionary.dict` as a base entry.
    Direct,
    /// The word was generated from a base word by applying a single affix flag.
    AffixGenerated {
        /// The affix flag character that generated this word.
        flag: char,
        /// Whether this was a prefix or suffix.
        kind: AffixEntryKind,
    },
    /// The word was generated via cross-product interaction between affix flags.
    CrossProduct {
        /// The first affix flag (applied to the base to create an intermediate word).
        first_flag: char,
        /// The second affix flag (applied to the intermediate word).
        second_flag: char,
    },
}

/// A record describing one route by which a word ends up in the dictionary.
#[derive(Debug, Clone)]
pub struct ProvenanceRecord {
    /// The generated word.
    pub word: String,
    /// The base dictionary entry that produced this word.
    pub base_word: String,
    /// The annotation flags on the base entry.
    pub base_annotations: String,
    /// How the word was generated.
    pub kind: ProvenanceKind,
}

impl AttributeList {
    fn into_human_readable(self) -> HumanReadableAttributeList {
        HumanReadableAttributeList {
            affixes: self
                .affixes
                .into_iter()
                .map(|(affix, exp)| (affix, exp.into_human_readable()))
                .collect(),
            properties: self.properties,
        }
    }

    pub fn parse(source: &str) -> Result<Self, Error> {
        let human_readable: Result<HumanReadableAttributeList, _> = serde_json::from_str(source);
        human_readable
            .map_err(Error::from)
            .and_then(|parsed| parsed.into_normal())
    }

    /// Expand an [`AnnotatedWord`] into a list of full words, including itself.
    ///
    /// This function processes a word and its attributes to:
    /// 1. Apply properties to the base word
    /// 2. Generate derived words using affix rules
    /// 3. Handle conditional expansions
    /// 4. Manage cross-product expansions
    ///
    /// # Arguments
    /// * `word` - The word to expand, along with its attributes
    /// * `dest` - The WordMap to store the expanded words and their metadata
    pub fn expand_annotated_word(&self, annotated_word: AnnotatedWord, word_map: &mut WordMap) {
        // Pre-allocate space in the destination map for better performance
        word_map.reserve(annotated_word.annotations.len() + 1);

        // Initialize base metadata that will be applied to all derived forms
        let mut base_metadata = DictWordMetadata::default();

        // Store metadata that should only be applied if certain conditions are met
        let orth_flags = OrthFlags::from_letters(&annotated_word.letters);
        base_metadata.orth_info = orth_flags;

        let mut conditional_expansion_metadata = Vec::new();

        // First pass: Process all properties to build the base metadata
        // Properties directly modify the word's metadata (e.g., part of speech, usage)
        for attr in &annotated_word.annotations {
            let Some(property) = self.properties.get(attr) else {
                continue;
            };
            base_metadata.merge(&property.metadata);
        }

        // Second pass: Process all affix rules to generate derived forms
        for attr in &annotated_word.annotations {
            // Skip if this attribute isn't an affix rule
            let Some(expansion) = self.affixes.get(attr) else {
                continue;
            };

            // Add any base metadata from this affix rule
            base_metadata.merge(&expansion.base_metadata);

            // Track new words generated by this affix rule
            let mut new_words: HashMap<CharString, DictWordMetadata> = HashMap::new();

            // Apply each replacement rule in this affix
            for replacement in &expansion.replacements {
                if let Some(replaced) =
                    Self::apply_replacement(replacement, &annotated_word.letters, expansion.kind)
                {
                    // Get or create metadata for this new word form
                    let metadata = new_words.entry(replaced.clone()).or_default();

                    // Process each target for this replacement
                    for target in &expansion.target {
                        if let Some(condition) = &target.if_base {
                            // Store conditional metadata to be applied later
                            conditional_expansion_metadata.push((
                                replaced.clone(),
                                target.metadata.clone(),
                                condition.clone(),
                            ));
                        } else {
                            // Apply target metadata immediately
                            metadata.merge(&target.metadata);
                        }
                    }
                }
            }

            // Handle cross-product expansions (e.g., both prefix and suffix)
            if expansion.cross_product {
                // Collect attributes that should be applied to the opposite affix type
                let mut opposite_attributes = Vec::new();

                // Add properties that should propagate to derived forms
                for attr in &annotated_word.annotations {
                    let Some(property) = self.properties.get(attr) else {
                        continue;
                    };
                    if expansion.kind == Prefix || property.propagate {
                        opposite_attributes.push(*attr);
                    }
                }

                // Add affix attributes of the opposite type
                for attr in &annotated_word.annotations {
                    let Some(attr_def) = self.affixes.get(attr) else {
                        continue;
                    };
                    // This checks if the current affix is of the opposite type
                    if (attr_def.kind != Prefix) != (expansion.kind != Prefix) {
                        opposite_attributes.push(*attr);
                    }
                }

                // Recursively process each new word form
                for (new_word, metadata) in new_words {
                    self.expand_annotated_word(
                        AnnotatedWord {
                            letters: new_word.clone(),
                            annotations: opposite_attributes.clone(),
                        },
                        word_map,
                    );
                    // Update the metadata of the expanded word
                    let target_metadata = word_map.get_metadata_mut_chars(&new_word).unwrap();
                    target_metadata.merge(&metadata);
                    target_metadata.derived_from =
                        Some(WordId::from_word_chars(&annotated_word.letters));
                }
            } else {
                // Simple case: no cross-product expansion needed
                for (key, mut value) in new_words.into_iter() {
                    value.derived_from = Some(WordId::from_word_chars(&annotated_word.letters));

                    if let Some(existing_metadata) = word_map.get_metadata_mut_chars(&key) {
                        // Merge with existing metadata
                        existing_metadata.merge(&value);
                    } else {
                        // Add new entry
                        word_map.insert(WordMapEntry {
                            canonical_spelling: key,
                            metadata: value,
                        });
                    }
                }
            }
        }

        // Finalize the metadata for the base word
        let mut full_metadata = base_metadata;

        // Merge with any existing metadata for this word
        if let Some(existing_metadata) = word_map.get_with_chars(&annotated_word.letters) {
            full_metadata.merge(&existing_metadata.metadata);
        }

        // Store the final metadata for the base word
        word_map.insert(WordMapEntry {
            metadata: full_metadata.clone(),
            canonical_spelling: annotated_word.letters,
        });

        // Process any conditional expansions
        for (letters, metadata, condition) in conditional_expansion_metadata {
            // Check if the condition is satisfied by the base word's metadata
            let condition_satisfied = full_metadata.or(&condition) == full_metadata;
            if !condition_satisfied {
                continue;
            }

            // Apply the conditional metadata
            word_map
                .get_metadata_mut_chars(&letters)
                .unwrap()
                .merge(&metadata);
        }
    }

    /// Expand an iterator of annotated words into strings.
    /// Note that this does __not__ guarantee that produced words will be
    /// unique.
    pub fn expand_annotated_words(
        &self,
        words: impl IntoIterator<Item = AnnotatedWord>,
        dest: &mut WordMap,
    ) {
        for word in words {
            self.expand_annotated_word(word, dest);
        }
    }

    fn apply_replacement(
        replacement: &AffixReplacement,
        letters: &[char],
        kind: AffixEntryKind,
    ) -> Option<CharString> {
        if replacement.condition.len() > letters.len() {
            return None;
        }

        let target_span = if kind == Suffix {
            Span::new(letters.len() - replacement.condition.len(), letters.len())
        } else {
            Span::new(0, replacement.condition.len())
        };

        let target_segment = target_span.get_content(letters);

        if replacement.condition.matches(target_segment) {
            let mut replaced_segment = letters.to_smallvec();
            let mut remove: CharString = replacement.remove.to_smallvec();

            if kind != Suffix {
                replaced_segment.reverse();
            } else {
                remove.reverse();
            }

            for c in &remove {
                let last = replaced_segment.last()?;

                if last == c {
                    replaced_segment.pop();
                } else {
                    return None;
                }
            }

            let mut to_add = replacement.add.to_vec();

            if kind != Suffix {
                to_add.reverse()
            }

            replaced_segment.extend(to_add);

            if kind != Suffix {
                replaced_segment.reverse();
            }

            return Some(replaced_segment);
        }

        None
    }

    /// Expand a single annotated word and record provenance information for every
    /// word it generates (including itself).
    ///
    /// Unlike [`Self::expand_annotated_word`], this method does not write to a
    /// [`WordMap`]; it returns a flat list of [`ProvenanceRecord`]s instead.
    fn expand_with_provenance_inner(
        &self,
        annotated_word: &AnnotatedWord,
        base_word: &str,
        base_annotations: &str,
        parent_flag: Option<char>,
    ) -> Vec<ProvenanceRecord> {
        let mut records = Vec::new();

        // Record the base word itself (only at the top-level call)
        if parent_flag.is_none() {
            records.push(ProvenanceRecord {
                word: annotated_word.letters.iter().collect(),
                base_word: base_word.to_string(),
                base_annotations: base_annotations.to_string(),
                kind: ProvenanceKind::Direct,
            });
        }

        // Process affix rules
        for attr in &annotated_word.annotations {
            let Some(expansion) = self.affixes.get(attr) else {
                continue;
            };

            // Track words generated by this flag to avoid duplicates within a flag
            let mut seen_for_flag = hashbrown::HashSet::new();

            // Apply each replacement rule in this affix
            for replacement in &expansion.replacements {
                if let Some(replaced) =
                    Self::apply_replacement(replacement, &annotated_word.letters, expansion.kind)
                {
                    let generated_word: String = replaced.iter().collect();

                    if !seen_for_flag.insert(generated_word.clone()) {
                        continue;
                    }

                    // Determine provenance kind based on whether this is a top-level
                    // or recursive (cross-product) call
                    let kind = if let Some(first_flag) = parent_flag {
                        ProvenanceKind::CrossProduct {
                            first_flag,
                            second_flag: *attr,
                        }
                    } else {
                        ProvenanceKind::AffixGenerated {
                            flag: *attr,
                            kind: expansion.kind,
                        }
                    };

                    records.push(ProvenanceRecord {
                        word: generated_word,
                        base_word: base_word.to_string(),
                        base_annotations: base_annotations.to_string(),
                        kind,
                    });
                }
            }

            // Handle cross-product: recursively expand with opposite-type affixes
            if expansion.cross_product {
                let mut opposite_attributes = Vec::new();

                // Add properties that should propagate to derived forms
                // (mirrors the logic in expand_annotated_word)
                for opp_attr in &annotated_word.annotations {
                    let Some(property) = self.properties.get(opp_attr) else {
                        continue;
                    };
                    if expansion.kind == Prefix || property.propagate {
                        opposite_attributes.push(*opp_attr);
                    }
                }

                // Collect opposite-type affixes
                for opp_attr in &annotated_word.annotations {
                    let Some(attr_def) = self.affixes.get(opp_attr) else {
                        continue;
                    };
                    if (attr_def.kind != Prefix) != (expansion.kind != Prefix) {
                        opposite_attributes.push(*opp_attr);
                    }
                }

                if !opposite_attributes.is_empty() {
                    // For each word generated by this affix, recursively expand with
                    // opposite-type affixes and record cross-product provenance.
                    for replacement in &expansion.replacements {
                        if let Some(replaced) = Self::apply_replacement(
                            replacement,
                            &annotated_word.letters,
                            expansion.kind,
                        ) {
                            let intermediate = AnnotatedWord {
                                letters: replaced,
                                annotations: opposite_attributes.clone(),
                            };
                            let cross_records = self.expand_with_provenance_inner(
                                &intermediate,
                                base_word,
                                base_annotations,
                                Some(*attr),
                            );
                            records.extend(cross_records);
                        }
                    }
                }
            }
        }

        records
    }

    /// Expand a single annotated word and return provenance records for every
    /// word it generates.
    pub fn expand_with_provenance(
        &self,
        annotated_word: &AnnotatedWord,
    ) -> Vec<ProvenanceRecord> {
        let base_word: String = annotated_word.letters.iter().collect();
        let base_annotations: String = annotated_word.annotations.iter().collect();
        self.expand_with_provenance_inner(annotated_word, &base_word, &base_annotations, None)
    }

    /// Expand all annotated words and return provenance records for every
    /// generated word.
    pub fn expand_all_with_provenance(
        &self,
        words: impl IntoIterator<Item = AnnotatedWord>,
    ) -> Vec<ProvenanceRecord> {
        let mut records = Vec::new();
        for word in words {
            records.extend(self.expand_with_provenance(&word));
        }
        records
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HumanReadableAttributeList {
    affixes: HashMap<char, HumanReadableExpansion>,
    properties: HashMap<char, Property>,
}

impl HumanReadableAttributeList {
    pub fn into_normal(self) -> Result<AttributeList, Error> {
        let mut affixes = HashMap::with_capacity(self.affixes.len());

        for (affix, expansion) in self.affixes.into_iter() {
            affixes.insert(affix, expansion.into_normal()?);
        }

        Ok(AttributeList {
            affixes,
            properties: self.properties,
        })
    }
}

#[cfg(test)]
mod tests {
    use crate::spell::{Dictionary, FstDictionary};

    #[test]
    fn proper_noun_property_propagates_to_plurals() {
        let fst_dict = FstDictionary::curated();
        if let Some(vw_plural) = fst_dict.get_word_metadata_str("Volkswagens") {
            assert!(vw_plural.is_proper_noun());
        }
    }

    #[test]
    fn proper_noun_propagates_to_possessives_2327() {
        if let Some(vw_possessive) = FstDictionary::curated().get_word_metadata_str("Volkswagen's")
        {
            assert!(vw_possessive.is_possessive_noun());
        }
    }

    #[test]
    fn provenance_direct_entry() {
        use super::super::tests::{TEST_AFFIX_JSON, TEST_WORD_LIST};
        use super::super::word_list::parse_word_list;
        use super::{AttributeList, ProvenanceKind};

        let words = parse_word_list(TEST_WORD_LIST).unwrap();
        let attributes = AttributeList::parse(&TEST_AFFIX_JSON.to_string()).unwrap();

        let all_records = attributes.expand_all_with_provenance(words);

        // "hello" has no annotations, so it should only appear as a direct entry
        let hello_records: Vec<_> = all_records
            .iter()
            .filter(|r| r.word == "hello")
            .collect();
        assert_eq!(hello_records.len(), 1);
        assert_eq!(hello_records[0].kind, ProvenanceKind::Direct);
        assert_eq!(hello_records[0].base_word, "hello");
    }

    #[test]
    fn provenance_affix_generated() {
        use super::super::expansion::AffixEntryKind;
        use super::super::tests::{TEST_AFFIX_JSON, TEST_WORD_LIST};
        use super::super::word_list::parse_word_list;
        use super::ProvenanceKind;
        use super::AttributeList;

        let words = parse_word_list(TEST_WORD_LIST).unwrap();
        let attributes = AttributeList::parse(&TEST_AFFIX_JSON.to_string()).unwrap();

        let all_records = attributes.expand_all_with_provenance(words);

        // "try" has flag B (suffix), which should generate "tried" via y→ied
        let tried_records: Vec<_> = all_records
            .iter()
            .filter(|r| r.word == "tried")
            .collect();
        assert!(!tried_records.is_empty(), "should have found 'tried'");
        assert_eq!(tried_records[0].base_word, "try");
        assert!(matches!(
            tried_records[0].kind,
            ProvenanceKind::AffixGenerated {
                flag: 'B',
                kind: AffixEntryKind::Suffix,
            }
        ));
    }

    #[test]
    fn provenance_cross_product() {
        use super::super::tests::{TEST_AFFIX_JSON, TEST_WORD_LIST};
        use super::super::word_list::parse_word_list;
        use super::{AttributeList, ProvenanceKind};

        let words = parse_word_list(TEST_WORD_LIST).unwrap();
        let attributes = AttributeList::parse(&TEST_AFFIX_JSON.to_string()).unwrap();

        let all_records = attributes.expand_all_with_provenance(words);

        // "work" has flags AB where A=re- prefix (cross_product=true) and B=-ed suffix
        // (cross_product=true).  So "reworked" should appear as a cross-product.
        let reworked_records: Vec<_> = all_records
            .iter()
            .filter(|r| r.word == "reworked")
            .collect();
        assert!(!reworked_records.is_empty(), "should have found 'reworked'");
        assert_eq!(reworked_records[0].base_word, "work");
        // It should be a cross-product (A then B, or B then A)
        assert!(
            reworked_records.iter().any(|r| matches!(
                r.kind,
                ProvenanceKind::CrossProduct { .. }
            )),
            "reworked should have at least one cross-product route"
        );
    }

    #[test]
    fn provenance_multi_route() {
        use super::super::tests::{TEST_AFFIX_JSON, TEST_WORD_LIST};
        use super::super::word_list::parse_word_list;
        use super::{AttributeList, ProvenanceKind};

        let words = parse_word_list(TEST_WORD_LIST).unwrap();
        let attributes = AttributeList::parse(&TEST_AFFIX_JSON.to_string()).unwrap();

        let all_records = attributes.expand_all_with_provenance(words);

        // "rework" should be reachable as:
        // 1. Direct prefix generation from "work" via A (re-)
        let rework_records: Vec<_> = all_records
            .iter()
            .filter(|r| r.word == "rework")
            .collect();
        assert!(!rework_records.is_empty(), "should have found 'rework'");

        // Check that it was generated via prefix A from "work"
        assert!(rework_records.iter().any(|r| matches!(
            &r.kind,
            ProvenanceKind::AffixGenerated { flag: 'A', .. }
        )));
    }

    #[test]
    fn provenance_base_word_always_direct() {
        use super::super::tests::{TEST_AFFIX_JSON, TEST_WORD_LIST};
        use super::super::word_list::parse_word_list;
        use super::{AttributeList, ProvenanceKind};

        let words = parse_word_list(TEST_WORD_LIST).unwrap();
        let attributes = AttributeList::parse(&TEST_AFFIX_JSON.to_string()).unwrap();

        let all_records = attributes.expand_all_with_provenance(words);

        // Every base word from the dictionary should appear as Direct
        for base in &["hello", "try", "work", "blank"] {
            let direct_records: Vec<_> = all_records
                .iter()
                .filter(|r| &r.word == base && r.kind == ProvenanceKind::Direct)
                .collect();
            assert!(
                !direct_records.is_empty(),
                "base word '{}' should have a Direct provenance record",
                base
            );
        }
    }
}
