// Auto-generated by build.rs - do not edit manually
//! Language support framework for Harper.
//!
//! This module provides the core types for supporting multiple languages in Harper,
//! including language families and specific language variants with dialects.
use crate::language::english::dialects::EnglishDialect;

#[cfg(feature = "de")]
use crate::language::german::dialects::GermanDialect;

#[cfg(feature = "pt")]
use crate::language::portuguese::dialects::PortugueseDialect;

#[cfg(feature = "sk")]
use crate::language::slovak::dialects::SlovakDialect;

use serde::{Deserialize, Serialize};
use strum_macros::{Display, EnumCount, EnumIter, EnumString};

/// Parse a language from a string representation.
pub fn parse_language(s: &str) -> Option<Language> {
    let s_lower = s.to_ascii_lowercase();

    match s_lower.as_str() {
        "us" | "usa" | "america" | "american" | "en-us" | "en_us" => {
            Some(Language::English(EnglishDialect::try_from_abbr("US").unwrap()))
        }
        "uk" | "gb" | "british" | "britain" | "en-gb" | "en_gb" => {
            Some(Language::English(EnglishDialect::try_from_abbr("GB").unwrap()))
        }
        "au" | "aus" | "australia" | "australian" | "en-au" | "en_au" => {
            Some(Language::English(EnglishDialect::try_from_abbr("AU").unwrap()))
        }
        "in" | "india" | "indian" | "bharat" | "en-in" | "en_in" => {
            Some(Language::English(EnglishDialect::try_from_abbr("IN").unwrap()))
        }
        "ca" | "canada" | "canadian" | "en-ca" | "en_ca" => {
            Some(Language::English(EnglishDialect::try_from_abbr("CA").unwrap()))
        }
        #[cfg(feature = "de")]
        "de" | "german" | "deutsch" | "de-de" | "de_de" => {
            Some(Language::German(GermanDialect::try_from_abbr("Standard").unwrap()))
        }
        #[cfg(feature = "de")]
        "at" | "austria" | "austrian" | "de-at" | "de_at" => {
            Some(Language::German(GermanDialect::try_from_abbr("Austrian").unwrap()))
        }
        #[cfg(feature = "de")]
        "ch" | "switzerland" | "swiss" | "de-ch" | "de_ch" => {
            Some(Language::German(GermanDialect::try_from_abbr("Swiss").unwrap()))
        }
        #[cfg(feature = "pt")]
        "pt" | "pt-pt" | "pt_pt" | "portuguese" | "português" => {
            Some(Language::Portuguese(PortugueseDialect::try_from_abbr("European").unwrap()))
        }
        #[cfg(feature = "pt")]
        "br" | "brazil" | "portuguese-brazilian" | "portuguese_brazilian" | "pt-br" | "pt_br" => {
            Some(Language::Portuguese(PortugueseDialect::try_from_abbr("Brazilian").unwrap()))
        }
        #[cfg(feature = "pt")]
        "ao" => {
            Some(Language::Portuguese(PortugueseDialect::try_from_abbr("African").unwrap()))
        }
        #[cfg(feature = "sk")]
        "sk" | "slovak" | "slovensko" | "sk-sk" | "sk_sk" => {
            Some(Language::Slovak(SlovakDialect::try_from_abbr("Standard").unwrap()))
        }
        _ => None,
    }
}

/// A specific language with its dialects.
#[derive(
    Debug, Clone, Copy, Serialize, Deserialize, PartialEq, PartialOrd, Eq, Hash, EnumCount, Display,
)]
pub enum Language {
    /// English language with its dialects
    English(EnglishDialect),
    /// German language with its dialects
    #[cfg(feature = "de")]
    German(GermanDialect),
    /// Portuguese language with its dialects
    #[cfg(feature = "pt")]
    Portuguese(PortugueseDialect),
    /// Slovak language with its dialects
    #[cfg(feature = "sk")]
    Slovak(SlovakDialect),
}

/// A family of languages.
#[derive(
    Default,
    Debug,
    Clone,
    Copy,
    Serialize,
    Deserialize,
    PartialEq,
    PartialOrd,
    Eq,
    Hash,
    EnumCount,
    EnumString,
    EnumIter,
    Display,
)]
pub enum LanguageFamily {
    #[default]
    English,
    #[cfg(feature = "de")]
    German,
    #[cfg(feature = "pt")]
    Portuguese,
    #[cfg(feature = "sk")]
    Slovak,
}

impl From<Language> for LanguageFamily {
    fn from(value: Language) -> Self {
        match value {
            Language::English(_) => Self::English,
            #[cfg(feature = "de")]
            Language::German(_) => Self::German,
            #[cfg(feature = "pt")]
            Language::Portuguese(_) => Self::Portuguese,
            #[cfg(feature = "sk")]
            Language::Slovak(_) => Self::Slovak,
        }
    }
}

impl LanguageFamily {
    pub fn dict_suffix(&self) -> &'static str {
        match self {
            Self::English => "",
            #[cfg(feature = "de")]
            Self::German => "-de",
            #[cfg(feature = "pt")]
            Self::Portuguese => "-pt",
            #[cfg(feature = "sk")]
            Self::Slovak => "-sk",
        }
    }
}

impl Language {
    pub fn family(&self) -> LanguageFamily {
        (*self).into()
    }
}

impl Default for Language {
    fn default() -> Self {
        Self::English(EnglishDialect::American)
    }
}
