// Auto-generated by build.rs - do not edit manually
// This file centralizes all language-specific conditional compilation

pub mod dialects;
pub mod languages;
pub mod module;
pub mod morphology;
pub mod registry;

pub mod english;

#[cfg(feature = "de")]
pub mod german;

#[cfg(feature = "pl")]
pub mod polish;

#[cfg(feature = "pt")]
pub mod portuguese;

#[cfg(feature = "sk")]
pub mod slovak;

pub use languages::{Language, LanguageFamily, all_languages, language_aliases, parse_language};
pub use module::{LanguageDetector, LanguageModule};
pub use morphology::{Agreement, Case, Gender, Mood, Morphology, MorphologyExt, Number};
pub use registry::{
    ProseLanguage, add_language_specific_linters, default_language, detect_language, dictionary,
    dictionary_for_language, language_stats, languages_with_stats, new_curated,
    new_curated_for_language, parser_for_prose, prose_language, weir_rules_lint_group,
};
