//! Weir rules for Portuguese.
//!
//! Generated by `build.rs` from the `.weir` files in this directory: the
//! `lint_group()` below and one test per rule, running its own `test` and
//! `allows` lines. Adding a rule file is the whole edit.
include!(env!("PORTUGUESE_WEIR_RULE_LIST"));
