#!/usr/bin/env python3
"""Give German infinitives their conjugation affix flags.

`dictionary.dict` carries the verb *reading* on the `V` property flag, but the
finite forms are generated by the affix flags `d` (-te), `f` (-e), `i` (-t) and
`j` (-en). 22592 verb entries carry all four; 843 infinitives carry `V` and none
of them, so they produce no finite forms at all and Harper flags "benutzte",
"beruhigte" and "bremste" as misspellings.

Most of the 843 were mechanically tagged `~~NMZV`: the noun compounding
interfixes plus a verb reading, with the conjugation never filled in.

Only infinitive-shaped bases are touched. The remaining ~5500 `V` entries
without conjugation flags are *already* inflected forms stored as their own
entry ("brachte", "berätst"); conjugating those again would yield "brachtete".

Two shapes are excluded because `V` there is a mistag rather than a verb:

  * bases whose stem is shorter than four characters ("bären/~~NV" is the plural
    of "Bär", "besen/~~NV" is "Besen"), where the generated forms would be
    nonsense and the stem is too short for the compound checker to break up;
  * bases already carrying `Z`-less noun plural flags with no other verbal
    evidence -- see `LIKELY_NOUN_PLURAL`.

Run from the repo root. `--apply` writes; the default is a dry run.
Re-running is idempotent.
"""

import argparse
import sys
from pathlib import Path

DICT = Path("harper-core/src/language/german/dictionary.dict")

# The conventional conjugation set: -te, -e, -t, -en. Matches the 22592 entries
# that already have it. `h` (-st) is deliberately not added: it doubles as the
# "vetted" bookkeeping marker on noun entries, so it is not a clean verb signal.
CONJUGATION = "dfij"

# Any of these means the entry already generates finite forms.
AFFIX_FLAGS = set("cdefij")

# Noun plurals mistagged `V`. Hand-audited: each is the plural of a common noun
# and has no verb reading at all.
LIKELY_NOUN_PLURAL = {
    "bären",
    "besen",
    "bissen",
    "boten",
    "damen",
    "daten",
    "farben",
    "fasern",
    "ferien",
    "flocken",
    "gaben",
    "garten",
    "gassen",
    "gnaden",
    "graben",
    "haufen",
    "hosen",
    "kosten",
    "kunden",
    "laden",
    "lagen",
    "listen",
    "massen",
    "noten",
    "quellen",
    "raten",
    "reihen",
    "rosen",
    "sachen",
    "samen",
    "seiten",
    "sorten",
    "stufen",
    "tanten",
    "themen",
    "tonnen",
    "waren",
    "wellen",
    "wochen",
    "zahlen",
    "zeiten",
}


def stem_of(word: str) -> str:
    """The conjugation stem the affix rules expect to build on."""
    if word.endswith(("ern", "eln")):
        return word[:-1]
    if word.endswith("en"):
        return word[:-2]
    return word


def should_conjugate(word: str, flags: str) -> bool:
    if "V" not in flags:
        return False
    if AFFIX_FLAGS & set(flags):
        return False
    if not word.endswith(("en", "ern", "eln")):
        return False
    if word.lower() in LIKELY_NOUN_PLURAL:
        return False
    return len(stem_of(word)) >= 4


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--apply", action="store_true", help="write the changes")
    args = parser.parse_args()

    if not DICT.exists():
        print(f"{DICT} not found -- run from the repo root", file=sys.stderr)
        return 1

    out = []
    changed = 0
    samples = []

    for line in DICT.read_text(encoding="utf-8").splitlines(keepends=True):
        body, sep, comment = line.partition("#")
        stripped = body.strip()
        if not stripped or "/" not in stripped:
            out.append(line)
            continue

        word, _, flags = stripped.partition("/")
        if not should_conjugate(word, flags.replace("~", "")):
            out.append(line)
            continue

        missing = "".join(c for c in CONJUGATION if c not in flags)
        if not missing:
            out.append(line)
            continue

        new_body = f"{word}/{flags}{missing}"
        # Keep the original spacing between the entry and any trailing comment.
        trailing = body[len(body.rstrip()) :]
        out.append(f"{new_body}{trailing}{sep}{comment}")
        changed += 1
        if len(samples) < 15:
            samples.append(f"{stripped}  ->  {new_body}")

    print(f"{changed} entries gain '{CONJUGATION}'")
    for s in samples:
        print(f"    {s}")

    if args.apply:
        DICT.write_text("".join(out), encoding="utf-8")
        print(f"wrote {DICT}")
    else:
        print("dry run; pass --apply to write")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
