#!/usr/bin/env python3

import json

def apply_verb_conversions():
    dict_file = "harper-core/src/language/german/dictionary.dict"
    
    # Load the conversion mapping
    with open('scripts/verb_conversion_detailed.json', 'r', encoding='utf-8') as f:
        conversion_map = json.load(f)
    
    # Read dictionary
    with open(dict_file, 'r', encoding='utf-8') as f:
        lines = f.readlines()
    
    print(f"Total conversion candidates: {len(conversion_map)}")
    
    # Calculate total savings
    total_savings = sum(len(info['removable_forms']) for info in conversion_map.values())
    print(f"Total words to be removed: {total_savings}")
    print(f"Total words to be added/modified: {len(conversion_map)}")
    print(f"Net reduction: {total_savings - len(conversion_map)} words")
    
    # Create a set of all words to keep (modified base forms + non-verb words + verb words not being converted)
    words_to_keep = set()
    modified_entries = []
    
    # Create a set of all words being converted
    converted_base_forms = set(conversion_map.keys())
    removed_forms = set()
    for info in conversion_map.values():
        removed_forms.update(info['removable_forms'])
    
    # Process each line
    for line in lines:
        line = line.strip()
        if not line or line.startswith('#') or line == '134791':
            modified_entries.append(line)
            continue
            
        parts = line.split('/')
        if len(parts) < 2:
            modified_entries.append(line)
            continue
            
        word = parts[0]
        flags_part = parts[1]
        flags = flags_part.split('#')[0].strip()
        comment = parts[2] if len(parts) > 2 else ''
        
        # Check if this word should be converted
        if word in conversion_map and '~~V' in flags:
            # This is a base form - modify it to use affix flags
            info = conversion_map[word]
            # Preserve existing flags and add the new affix flags
            existing_flags = flags.replace('~~V', '').strip()
            if existing_flags.startswith('~'):
                # Already has other flags, append the affix flags
                new_flags = f"~~V{existing_flags}{info['affix_flags']}"
            else:
                new_flags = f"~~V{info['affix_flags']}"
            if comment:
                new_line = f"{word}/{new_flags} # {comment}"
            else:
                new_line = f"{word}/{new_flags}"
            modified_entries.append(new_line)
            words_to_keep.add(word)
        elif word in removed_forms and '~~V' in flags:
            # This word should be removed (it will be generated by affix rules) - but only if it's a verb
            info = None
            for base_form, base_info in conversion_map.items():
                if word in base_info['removable_forms']:
                    info = base_info
                    break
            
            if info:
                base_word = info['base'] + 'en'  # typically the infinitive
                comment_text = f"REMOVED: now generated by {base_word}/~~V{info['affix_flags']}"
                modified_entries.append(f"#{comment_text}")
            else:
                # Fallback - just comment it out
                modified_entries.append(f"# REMOVED: {line}")
        else:
            # Keep as is
            modified_entries.append(line)
    
    # Count the results
    original_count = len([line for line in lines if line.strip() and not line.startswith('#') and line.strip() != '134791'])
    new_count = len([line for line in modified_entries if line.strip() and not line.startswith('#') and line.strip() != '134791'])
    
    print(f"Original dictionary entries: {original_count}")
    print(f"New dictionary entries: {new_count}")
    print(f"Reduction: {original_count - new_count} entries")
    
    # Update the count at the top of the file
    final_entries = []
    for line in modified_entries:
        if line.strip() == '134791':
            final_entries.append(f"{new_count}")
        else:
            final_entries.append(line)
    
    # Write the modified dictionary
    with open(dict_file, 'w', encoding='utf-8') as f:
        f.write('\n'.join(final_entries) + '\n')
    
    print("Dictionary updated successfully!")
    
    # Show some examples of changes
    print("\nExamples of converted verbs:")
    for base_form, info in list(conversion_map.items())[:10]:
        print(f"  {base_form}: ~~V -> ~~V{info['affix_flags']} (removed: {info['removable_forms']})")

if __name__ == "__main__":
    apply_verb_conversions()