#!/usr/bin/env python3

import json

def apply_verb_conversions_v2():
    dict_file = "harper-core/src/language/german/dictionary.dict"
    
    # Load the conversion mapping
    with open('scripts/verb_conversion_detailed.json', 'r', encoding='utf-8') as f:
        conversion_map = json.load(f)
    
    # Read dictionary
    with open(dict_file, 'r', encoding='utf-8') as f:
        lines = f.readlines()
    
    print(f"Total conversion candidates: {len(conversion_map)}")
    
    # Calculate total savings
    total_savings = sum(len(info['removable_forms']) for info in conversion_map.values())
    print(f"Total words to be removed: {total_savings}")
    print(f"Total stem words to be added: {len(conversion_map)}")
    print(f"Net reduction: {total_savings - len(conversion_map)} words")
    
    # Create new entries for stem forms and remove conjugated forms
    modified_entries = []
    
    # Create a set of all words to be removed
    removed_forms = set()
    for info in conversion_map.values():
        removed_forms.update(info['removable_forms'])
    
    # Create a mapping from full form to stem form
    full_to_stem = {}
    for base_form, info in conversion_map.items():
        stem = info['base']
        full_to_stem[base_form] = stem
        # Also map all removable forms to this stem
        for removable_form in info['removable_forms']:
            full_to_stem[removable_form] = stem
    
    # Process each line
    for line in lines:
        line = line.strip()
        if not line or line.startswith('#') or line == '134791':
            modified_entries.append(line)
            continue
            
        parts = line.split('/')
        if len(parts) < 2:
            modified_entries.append(line)
            continue
            
        word = parts[0]
        flags_part = parts[1]
        flags = flags_part.split('#')[0].strip()
        comment = parts[2] if len(parts) > 2 else ''
        
        # Check if this word should be converted to a stem form
        if word in conversion_map and '~~V' in flags:
            # This is a base form - replace it with the stem form
            info = conversion_map[word]
            stem = info['base']
            combined_flags = f"~~V{info['affix_flags']}"
            
            # Add the stem form with the combined flags
            if comment:
                new_line = f"{stem}/{combined_flags} # {comment} # REPLACES {word}"
            else:
                new_line = f"{stem}/{combined_flags} # REPLACES {word}"
            modified_entries.append(new_line)
            
            # Also add a comment for the original form
            modified_entries.append(f"# REMOVED: {word} now generated by {stem}/{combined_flags}")
            
        elif word in removed_forms and '~~V' in flags:
            # This word should be removed (it will be generated by affix rules)
            # Check if we already added a comment for this
            if word not in full_to_stem:
                # Fallback - just comment it out
                modified_entries.append(f"# REMOVED: {line}")
            # If it's in full_to_stem, the stem form will handle it, so we just skip
        else:
            # Keep as is
            modified_entries.append(line)
    
    # Count the results
    original_count = len([line for line in lines if line.strip() and not line.startswith('#') and line.strip() != '134791'])
    new_count = len([line for line in modified_entries if line.strip() and not line.startswith('#') and line.strip() != '134791'])
    
    print(f"Original dictionary entries: {original_count}")
    print(f"New dictionary entries: {new_count}")
    print(f"Reduction: {original_count - new_count} entries")
    
    # Update the count at the top of the file
    final_entries = []
    for line in modified_entries:
        if line.strip() == '134791':
            final_entries.append(f"{new_count}")
        else:
            final_entries.append(line)
    
    # Write the modified dictionary
    with open(dict_file, 'w', encoding='utf-8') as f:
        f.write('\n'.join(final_entries) + '\n')
    
    print("Dictionary updated successfully!")
    
    # Show some examples of changes
    print("\nExamples of converted verbs:")
    for base_form, info in list(conversion_map.items())[:10]:
        stem = info['base']
        print(f"  {base_form} -> {stem}/~~V{info['affix_flags']} (removed: {info['removable_forms']})")

if __name__ == "__main__":
    apply_verb_conversions_v2()