#!/usr/bin/env python3
"""
Clean up redundant auto-added entries that can be generated by the FST system.
"""

import re
from collections import defaultdict

def main():
    with open('harper-core/src/language/german/dictionary.dict', 'r') as f:
        lines = f.readlines()
    
    # First pass: build a map of base words to their annotations
    base_words = {}
    
    for i, line in enumerate(lines):
        line = line.strip()
        if not line or line.startswith('#') or '# auto-added' in line or '# auto-converted' in line:
            continue
        
        # Parse word/annotations # comment
        match = re.match(r'^([^/]+)/(~~[^\s]+)\s*(#.*)?$', line)
        if match:
            word = match.group(1)
            annotations = match.group(2)
            base_words[word] = annotations
    
    print(f"Base words: {len(base_words)}")
    
    # Second pass: identify auto-added entries that can be generated from base words
    redundant_entries = []
    
    # Common adjective endings that should be generated by JOQRSTUW annotations
    adjective_endings = ['e', 'em', 'en', 'er', 'es', 'sten']
    
    # Common noun endings that should be generated by X, Y, a, b, etc. annotations
    noun_endings = ['e', 'n', 'en', 'er', 's', 'es']
    
    for i, line in enumerate(lines):
        line = line.strip()
        if '# auto-added' not in line or not line:
            continue
            
        # Parse word/annotations # comment
        match = re.match(r'^([^/]+)/(~~[^\s]+)\s*(#.*)?$', line)
        if match:
            word = match.group(1)
            auto_annotations = match.group(2)
            
            # Check if this word can be generated from a base word
            can_be_generated = False
            
            # Check adjective inflections
            for ending in adjective_endings:
                if word.endswith(ending):
                    base = word[:-len(ending)]
                    if base in base_words:
                        base_annotations = base_words[base]
                        # Check if base has adjective properties that can generate this ending
                        if ('J' in base_annotations and ending in ['e', 'em', 'en', 'er', 'es']) or \
                           ('U' in base_annotations and ending == 'er') or \
                           ('W' in base_annotations and ending == 'sten'):
                            can_be_generated = True
                            break
            
            # Check noun inflections
            if not can_be_generated:
                for ending in noun_endings:
                    if word.endswith(ending):
                        base = word[:-len(ending)]
                        if base in base_words:
                            base_annotations = base_words[base]
                            # Check if base has noun properties that can generate this ending
                            if ('X' in base_annotations and ending == 'e') or \
                               ('Y' in base_annotations and ending in ['n', 'en']) or \
                               ('a' in base_annotations and ending == 'er') or \
                               ('b' in base_annotations and ending == 's') or \
                               ('N' in base_annotations and ending == 'es'):
                                can_be_generated = True
                                break
            
            if can_be_generated:
                redundant_entries.append((i+1, line, word))
    
    print(f"Redundant auto-added entries: {len(redundant_entries)}")
    
    # Show some examples
    for line_num, line, word in redundant_entries[:20]:
        print(f"  Line {line_num}: {word} -> {line}")
    
    # Apply the changes
    if redundant_entries:
        modified_lines = lines.copy()
        
        for line_num, old_line, word in redundant_entries:
            modified_lines[line_num-1] = ''
        
        # Update the word count
        non_empty_lines = [line for line in modified_lines[1:] if line.strip() and not line.strip().startswith('#')]
        new_word_count = len(non_empty_lines)
        modified_lines[0] = f"{new_word_count}\n"
        
        # Write the changes
        with open('harper-core/src/language/german/dictionary.dict', 'w') as f:
            f.writelines(modified_lines)
        
        print(f"\nRemoved {len(redundant_entries)} redundant entries")
        print(f"New word count: {new_word_count}")
        print(f"Reduction: {len(lines) - 1 - new_word_count} words")
    else:
        print("No redundant entries found to remove")

if __name__ == '__main__':
    main()