// Build script for harper-wasm
// This script generates the Dialect enum based on language configurations from harper-core

use std::env;
use std::fs;
use std::path::Path;

/// Convert a string to PascalCase
fn to_pascal_case(s: &str) -> String {
    s.split('_')
        .map(|part| {
            let mut chars = part.chars();
            match chars.next() {
                None => String::new(),
                Some(first) => {
                    let mut result = first.to_ascii_uppercase().to_string();
                    result.extend(chars.map(|c| c.to_ascii_lowercase()));
                    result
                }
            }
        })
        .collect()
}

/// Convert a dialect name for use in the Dialect enum variant
/// Preserves uppercase for short codes (like PT, BR, AO) and converts others to PascalCase
fn to_dialect_variant(dialect_name: &str) -> String {
    // If the dialect name is all uppercase (like PT, BR, AO), keep it as-is
    if dialect_name.chars().all(|c| c.is_ascii_uppercase()) {
        dialect_name.to_string()
    } else {
        // Otherwise convert to PascalCase
        to_pascal_case(dialect_name)
    }
}

fn main() {
    // Discover the manifest directory
    let manifest_dir = Path::new(env!("CARGO_MANIFEST_DIR"));

    // Path to harper-core's language directory
    let language_dir = manifest_dir
        .parent()
        .unwrap()
        .join("harper-core/src/language");

    // Generate the Dialect enum
    let mut code = String::new();
    code.push_str("// Auto-generated by harper-wasm build.rs - do not edit manually\n");
    code.push_str("// This file provides the Dialect enum for harper-wasm.\n");
    code.push_str("// It is auto-generated from harper-core's language configurations\n");
    code.push_str("// to ensure all languages are automatically supported.\n\n");

    // Generate the Dialect enum
    code.push_str("/// Specifies a dialect, often used for linting.\n");
    code.push_str("#[wasm_bindgen]\n");
    code.push_str("#[derive(Serialize, Deserialize, Debug, Clone, Copy)]\n");
    code.push_str("pub enum Dialect {\n");

    // English dialects - always included
    code.push_str("    // English dialects\n");
    code.push_str("    American,\n");
    code.push_str("    British,\n");
    code.push_str("    Australian,\n");
    code.push_str("    Canadian,\n");
    code.push_str("    Indian,\n");

    // Check if language directory exists
    if language_dir.exists() && language_dir.is_dir() {
        // Read directory entries
        if let Ok(entries) = fs::read_dir(&language_dir) {
            // Sort entries for deterministic ordering
            let mut sorted_entries: Vec<_> = entries
                .filter_map(Result::ok)
                .filter(|entry| entry.path().is_dir())
                .collect();
            sorted_entries.sort_by_key(|entry| entry.path());

            // Known non-language directories to skip
            let non_language_dirs = ["dialects", "testing_framework"];

            for entry in sorted_entries {
                let dir_name = match entry.file_name().to_str() {
                    Some(name) => name.to_string(),
                    None => continue,
                };

                // Skip non-language directories
                if non_language_dirs.contains(&dir_name.as_str()) {
                    continue;
                }

                // Skip directories that don't contain language modules (look for module.rs)
                let module_path = entry.path().join("module.rs");
                if !module_path.exists() {
                    continue;
                }

                // Try to load config.toml
                let config_path = entry.path().join("config.toml");
                if !config_path.exists() {
                    continue;
                }

                let content = match fs::read_to_string(&config_path) {
                    Ok(c) => c,
                    Err(_) => continue,
                };

                // Try to parse as TOML table
                let table = match content.parse::<toml::Table>() {
                    Ok(t) => t,
                    Err(_) => continue,
                };

                // Extract language section
                let language_table = match table.get("language") {
                    Some(toml::Value::Table(t)) => t,
                    _ => continue,
                };

                let name = match language_table.get("name").and_then(|v| v.as_str()) {
                    Some(n) => n.to_string(),
                    None => continue,
                };

                // Skip English as it's already handled
                if dir_name == "english" {
                    continue;
                }

                // Extract dialects
                let dialects =
                    if let Some(toml::Value::Array(dialects_array)) = table.get("dialects") {
                        // Array of tables format: [[dialects]], [[dialects]], ...
                        let mut result = Vec::new();
                        for dialect_table in dialects_array {
                            if let toml::Value::Table(table) = dialect_table
                                && let Some(toml::Value::String(name)) = table.get("name")
                            {
                                result.push(name.clone());
                            }
                        }
                        result
                    } else {
                        Vec::new()
                    };

                if dialects.is_empty() {
                    continue;
                }

                // Generate variants for this language
                code.push_str(&format!("    // {} dialects\n", name));
                for dialect_name in dialects {
                    let dialect_variant = to_dialect_variant(&dialect_name);
                    let variant = format!("{}{}", name, dialect_variant);
                    code.push_str(&format!("    {},\n", variant));
                }
            }
        }
    }

    code.push_str("}\n");

    // Write the file
    let src_dir = manifest_dir.join("src");
    fs::create_dir_all(&src_dir).unwrap();
    let dest = src_dir.join("generated_dialect.rs");

    // Only write if the file doesn't exist, to avoid race conditions with harper-core's build
    // which may also generate this file. If harper-core has already generated it, we skip.
    // This allows both build scripts to run without conflicts.
    if !dest.exists() {
        fs::write(&dest, &code).unwrap();
    }

    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=src/generated_dialect.rs");
}
