// Build script for harper-wasm
// This script generates the Dialect enum based on the enabled features

use std::env;
use std::fs;
use std::path::Path;

fn main() {
    // Discover the manifest directory
    let manifest_dir = Path::new(env!("CARGO_MANIFEST_DIR"));

    // Generate the Dialect enum
    let mut code = String::new();
    code.push_str("// Auto-generated by harper-wasm build.rs - do not edit manually\n");
    code.push_str("// This file provides the Dialect enum for harper-wasm.\n\n");
    code.push_str("/// Specifies a dialect, often used for linting.\n");
    code.push_str("#[wasm_bindgen]\n");
    code.push_str("#[derive(Serialize, Deserialize, Debug, Clone, Copy)]\n");
    code.push_str("pub enum Dialect {\n");

    // English dialects - always included
    code.push_str("    // English dialects\n");
    code.push_str("    American,\n");
    code.push_str("    British,\n");
    code.push_str("    Australian,\n");
    code.push_str("    Canadian,\n");
    code.push_str("    Indian,\n");

    // German dialects - feature gated
    code.push_str("    // German dialects\n");
    code.push_str("    GermanStandard,\n");
    code.push_str("    GermanAustrian,\n");
    code.push_str("    GermanSwiss,\n");

    // Portuguese dialects - feature gated
    code.push_str("    // Portuguese dialects\n");
    code.push_str("    PortuguesePT,\n");
    code.push_str("    PortugueseBR,\n");
    code.push_str("    PortugueseAO,\n");

    // Slovak dialects - feature gated
    code.push_str("    // Slovak dialects\n");
    code.push_str("    SlovakStandard,\n");

    code.push_str("}\n");

    // Write the file
    let src_dir = manifest_dir.join("src");
    fs::create_dir_all(&src_dir).unwrap();
    let dest = src_dir.join("generated_dialect.rs");
    fs::write(&dest, &code).unwrap();

    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=src/generated_dialect.rs");
}
