[package]
name = "harper-brill"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
rs-conllu = "0.3.0"
harper-core = { path = "../harper-core", version = "*" }
tabled = "0.19.0"
hashbrown = "0.15.3"
strum = "0.27.1"
strum_macros = "0.27.1"
