name: Build Artifacts

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  merge_group:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-artifacts:
    runs-on: ${{ matrix.platform }}
    name: ${{ matrix.platform }} - just ${{ matrix.task }}
    strategy:
      matrix:
        include:
          - platform: 'ubuntu-latest'
            task: build-linux
          - platform: 'windows-latest'
            task: build-windows
          - platform: 'macos-latest'
            task: build-macos
    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v2
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt,clippy
      - name: Install Node.js
        uses: actions/setup-node@v4
      - name: Enable Corepack
        run: corepack enable
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.7.8
      - uses: cargo-bins/cargo-binstall@main
      - name: Install APT packages
        if: matrix.platform == 'ubuntu-latest'
        run: sudo apt update && sudo apt install libwebkit2gtk-4.1-dev build-essential curl wget file libxdo-dev libssl-dev libayatana-appindicator3-dev librsvg2-dev -y
      - name: Install `wasm-pack`
        run: cargo binstall wasm-pack --force --no-confirm
      - name: Install `cargo tauri`
        run: cargo binstall tauri-cli --force --no-confirm
      - name: Install `cargo hack`
        run: cargo binstall cargo-hack --force --no-confirm
      - name: Run `${{ matrix.task }}`
        run: just ${{ matrix.task }}
