name: Check all features

on:
  push:
    branches: ["master", "web-prod"]
  pull_request:
    branches: ["master"]
  merge_group:

env:
  CARGO_TERM_COLOR: always

jobs:
  # make sure all crates work with all features enabled/disabled
  features:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup update --no-self-update stable && rustup default stable
      - uses: taiki-e/install-action@cargo-hack
      - run: cargo hack check --each-feature
