name: WordPress Plugin

on:
  push:
    branches: ["master"]
    tags: ["v*"]
  pull_request:
    branches: ["master"]
  merge_group:

env:
  CARGO_TERM_COLOR: always

jobs:
  wp-plugin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@dd310ad5a97d8e7b41793f8ef055398d51ad4de6 # v2.0.0
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".node-version"
      - name: Enable Corepack
        run: corepack enable
      - uses: cargo-bins/cargo-binstall@f8810ffa11196f23afb38e6fb64716fbf814ad8f # main
      - name: Install wasm-pack
        run: cargo binstall wasm-pack --force --no-confirm
      - name: Build
        run: just build-wp
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: harper.zip
          path: packages/wordpress-plugin/harper.zip
      - name: Draft GitHub release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: ncipollo/release-action@339a81892b84b4eeb0f6e744e4574d79d0d9b8dd # v1.21.0
        with:
          artifacts: packages/wordpress-plugin/harper.zip
          allowUpdates: true
          draft: true
