#!/usr/bin/env python3
"""Give German verbs their conjugation affix flags.

`dictionary.dict` stores no finite verb forms; they are generated by the affix
flags `d` (-te), `e` (-ten), `f` (-e), `i` (-t), `j` (-en) and `G` (-st). An entry without
them produces no finite forms at all, and Harper then reports "diente",
"promovierte" and "herrschte" as misspellings.

Which entries are verbs cannot be read off the dictionary itself: the `V`
property is missing from plenty of them ("promovieren/~~Nh", "herrschen/~~XZ")
and wrong on plenty of nouns. So the decision is made against hunspell, which
knows the inflected forms this file is trying to produce. A flag is added only
when hunspell accepts *every* form that flag would generate — each flag judged on
its own, so a verb still gets the tenses it does have.

The forms are computed by reading the rules out of `annotations.json` and
applying them here, rather than from a second hand-written copy of German verb
morphology. That matters: the rules encode the epenthetic `e` ("arbeit-e-te",
"öffn-e-te") through *how much* of the infinitive they strip, and a paraphrase
that got it wrong would silently skip every verb with a `d`- or `t`-final stem.

The match is deliberately case sensitive, and that is what keeps noun plurals
out: German verbs are lower case, nouns are capitalized. "bären" would otherwise
be conjugated to "bärte" on the strength of hunspell's "Bärte" — the plural of
"Bart", not a verb form at all.

Generate the form list once (it is large, and not committed):

    unmunch /usr/share/hunspell/de_DE.dic /usr/share/hunspell/de_DE.aff > forms.txt

Run from the repo root:

    harper-core/src/language/german/scripts/add_german_verb_conjugation_flags.py --forms forms.txt [--apply]

`--apply` writes; the default is a dry run. Re-running is idempotent.
"""

import argparse
import json
import sys
from pathlib import Path

DICT = Path("harper-core/src/language/german/dictionary.dict")
ANNOTATIONS = Path("harper-core/src/language/german/annotations.json")

# The conjugation set this script fills in: -te, -ten, -e, -t, -en, -st. The
# second person lives on `G` rather than `h`, because `h` is the compound
# marker that sits on nearly every noun and is no signal of a verb at all.
CONJUGATION = "defijG"

# Any of these means the entry already generates finite forms.
AFFIX_FLAGS = set("cdefijG")

# Noun plurals mistagged `V`. Hand-audited: each is the plural of a common noun
# and has no verb reading at all. The oracle rejects most of them on its own;
# this is a second line of defence.
LIKELY_NOUN_PLURAL = {
    "bären", "besen", "bissen", "boten", "damen", "daten", "farben", "fasern",
    "ferien", "flocken", "gaben", "garten", "gassen", "gnaden", "graben",
    "haufen", "hosen", "kosten", "kunden", "laden", "lagen", "listen",
    "massen", "noten", "quellen", "raten", "reihen", "rosen", "sachen",
    "samen", "seiten", "sorten", "stufen", "tanten", "themen", "tonnen",
    "waren", "wellen", "wochen", "zahlen", "zeiten",
}


def parse_condition(condition: str) -> list:
    """Compile an affix condition into one predicate per character position.

    Supports exactly what `spell::rune::matcher` supports: a literal, `.`, an
    `[abc]` class and a `[^abc]` negated class.
    """
    slots = []
    i = 0
    while i < len(condition):
        ch = condition[i]
        if ch == ".":
            slots.append(lambda c: True)
            i += 1
        elif ch == "[":
            end = condition.index("]", i)
            body = condition[i + 1 : end]
            negated = body.startswith("^")
            members = set(body[1:] if negated else body)
            if negated:
                slots.append((lambda m: (lambda c: c not in m))(members))
            else:
                slots.append((lambda m: (lambda c: c in m))(members))
            i = end + 1
        else:
            slots.append((lambda want: (lambda c: c == want))(ch))
            i += 1
    return slots


def condition_matches(word: str, slots: list) -> bool:
    """Does `word` end in a window matching `slots`?"""
    if len(word) < len(slots):
        return False
    tail = word[len(word) - len(slots) :]
    return all(slot(c) for slot, c in zip(slots, tail))


def load_rules(annotations: Path) -> dict:
    """flag -> list of (compiled condition, strip, add), for the flags we add."""
    data = json.loads(annotations.read_text(encoding="utf-8"))
    rules = {}
    for flag in CONJUGATION:
        expansion = data["affixes"][flag]
        if expansion.get("kind") != "suffix":
            raise SystemExit(f"flag {flag} is not a suffix rule")
        rules[flag] = [
            (parse_condition(r["condition"]), r["remove"], r["add"])
            for r in expansion["replacements"]
        ]
    return rules


def forms_for(word: str, replacements: list) -> list[str]:
    """Every surface form one flag's replacements produce for `word`."""
    out = []
    for slots, strip, add in replacements:
        if not condition_matches(word, slots):
            continue
        if strip and not word.endswith(strip):
            continue
        stem = word[: len(word) - len(strip)] if strip else word
        out.append(stem + add)
    return out


def infinitive_shaped(word: str) -> bool:
    return word.endswith(("en", "ern", "eln"))


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--apply", action="store_true", help="write the changes")
    parser.add_argument(
        "--forms",
        required=True,
        type=Path,
        help="hunspell form list from `unmunch` (see the module docstring)",
    )
    args = parser.parse_args()

    for path in (DICT, ANNOTATIONS, args.forms):
        if not path.exists():
            print(f"{path} not found -- run from the repo root", file=sys.stderr)
            return 1

    forms = {
        line.strip()
        for line in args.forms.read_text(encoding="utf-8", errors="replace").splitlines()
        if line.strip()
    }
    rules = load_rules(ANNOTATIONS)
    print(f"{len(forms)} hunspell forms, rules loaded for flags {CONJUGATION}")

    out = []
    entries_changed = 0
    flags_added = 0
    samples = []

    for line in DICT.read_text(encoding="utf-8").splitlines(keepends=True):
        body, sep, comment = line.partition("#")
        stripped = body.strip()
        if not stripped or "/" not in stripped:
            out.append(line)
            continue

        word, _, flags = stripped.partition("/")
        plain = flags.replace("~", "")
        lower = word.lower()

        if not infinitive_shaped(lower) or lower in LIKELY_NOUN_PLURAL:
            out.append(line)
            continue

        # Nothing to do if the entry already has the whole set. A partial set is
        # not a reason to stop: most verbs were given `dfij` before `e` (-ten)
        # was filled in, so the preterite plural is missing from all of them.
        if all(flag in plain for flag in CONJUGATION):
            out.append(line)
            continue

        # Case sensitive on purpose: a capitalized hunspell form is a noun, and
        # accepting it here is how noun plurals sneak in.
        def verified(flag: str) -> bool:
            produced = forms_for(lower, rules[flag])
            return bool(produced) and all(form in forms for form in produced)

        # Only the `t` endings are evidence. `j` (-en) regenerates an `-en`
        # entry unchanged, so hunspell accepts it for every noun plural in the
        # file — "Aufklärungen" would pass on the strength of "Aufklärungen".
        # `f` (-e) is nearly as weak. Require the tenses first, then take
        # whichever of the five the rules actually produce.
        if not all(verified(flag) for flag in "dei"):
            out.append(line)
            continue

        # The list also carries lower-case *noun* forms, because compounding
        # needs them, so "every form is in the list, in lower case" is not on its
        # own proof of a verb: "Konzern" would be conjugated on the strength of
        # "konzert" and "konzerte". A real verb form has no capitalized twin —
        # require at least one.
        tense_forms = {f for flag in "dei" for f in forms_for(lower, rules[flag])}
        if all(f.capitalize() in forms for f in tense_forms):
            out.append(line)
            continue

        missing = "".join(
            flag for flag in CONJUGATION if flag not in plain and verified(flag)
        )

        if not missing:
            out.append(line)
            continue

        new_body = f"{word}/{flags}{missing}"
        trailing = body[len(body.rstrip()) :]
        out.append(f"{new_body}{trailing}{sep}{comment}")
        entries_changed += 1
        flags_added += len(missing)
        if len(samples) < 12:
            shown = ", ".join(forms_for(lower, rules["d"]) + forms_for(lower, rules["i"]))
            samples.append(f"{stripped}  ->  {new_body}   ({shown})")

    print(f"{entries_changed} entries gain a conjugation flag, {flags_added} flags in total")
    for s in samples:
        print(f"    {s}")

    if args.apply:
        DICT.write_text("".join(out), encoding="utf-8")
        print(f"wrote {DICT}")
    else:
        print("dry run; pass --apply to write")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
