#!/usr/bin/env python3
"""Extract the forms igerman98 lets stand in front of a compound boundary.

hunspell's German dictionary does not let any word open a compound. An entry
opens one only when it carries `j` (COMPOUNDBEGIN via `SFX j`) or `x`, and it
stands in the middle only with `i`, `e`, `k` or `y`. The linking element is
part of the listed form, and the forms that exist only for compounding are
pseudo-roots of their own (`Arbeits/hij`, `Kinder/hij`, `Entscheidungs/hij`):

    Arbeit/Pm         no j   -> *Arbeitzeit
    Arbeits/hij       j      -> Arbeitszeit
    Festplatten/hij   j      -> Festplattenspeicher, not *Festplattespeicher

Harper tries every interfix after every element, which is how `Arbeitspeicher`
and `Versionhinweis` pass. `interfix_matches_known_begin` in
`spell/compound_checker.rs` reads the list this script writes: where igerman98
records how an element links, Harper requires that link; where it records
nothing (`Kasus`, `Lipid`), Harper keeps guessing.

    harper-core/src/language/german/scripts/extract_german_compound_begin_forms.py --hunspell-dict <UTF-8 de_DE>

The source is the igerman98-derived `de_DE` that the rest of `dictionary.dict`
was imported from; the list is written lower case, one form per line.
"""

import argparse
import pathlib

ROOT = pathlib.Path(__file__).resolve().parents[5]
OUT = ROOT / "harper-core/src/language/german/compound_begin_forms.txt"

# COMPOUNDBEGIN directly (`x`) or through `SFX j`; COMPOUNDMIDDLE directly
# (`y`) or through `PFX i`, `SFX e`, `PFX k`.
LINKING_FLAGS = set("jxieky")

HEADER = """\
# Forms that igerman98 (hunspell de_DE) lets stand in front of a compound
# boundary, lower case. Generated by
# harper-core/src/language/german/scripts/extract_german_compound_begin_forms.py
# from the same igerman98 dictionary dictionary.dict was imported from
# (GPLv2/GPLv3, Björn Jacke). Do not edit by hand.
"""


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--hunspell-dict", required=True, help="path to a UTF-8 de_DE, without extension")
    args = parser.parse_args()

    path = pathlib.Path(f"{args.hunspell_dict}.dic")
    forms = set()
    for line in path.read_text(encoding="utf-8", errors="replace").splitlines()[1:]:
        word, _, flags = line.strip().partition("/")
        if not word.isalpha():
            continue
        if set(flags) & LINKING_FLAGS:
            forms.add(word.lower())

    OUT.write_text(HEADER + "".join(f"{form}\n" for form in sorted(forms)), encoding="utf-8")
    print(f"wrote {len(forms)} forms to {OUT}")


if __name__ == "__main__":
    main()
